module.exports = {
  openPackTab: "#Openpackages_Tab",
  awardedTOTab: "#Awardedtaskorders_Tab",
  statusChip:"#StatusChip0",
  archiveTab: "#Archive_Tab",
  allPackageTab: "#Allpackages_Tab",
  packagecards: "#PackageCards ._package-title",  
  package0:"#Package0",
  packagecardName: "#Package0 ._package-title",  
  acquisitionStatusChip: "#PackageCards .v-chip--label",
  searchPackageInput: "#SearchPackages_SearchInput",
  searchResultSelector: "#Package0 #PortfolioName",
  searchBtn: "#SearchPackages_SearchButton",
  packageSortDropdown: "#PackageSort_dropdown",
  packageSortListItems: "#PackageSort_dropdown_field_control .v-menu__content .v-list",
  recentlyModified:"#PackageSort_DropdownListItem_Recentlymodified",
  card0MenuBtn: "#CardMenu0Button_0",
  statusChip0: "#StatusChip0",
  percent0: "#Percentage0",
  createdBy0: "#CreatedBy0",
  modified0: "#ModifiedOrArchived0",
  taskorderNo0:"#TaskOrder0",
  card0menuList: "#CardMenu0_0  .v-list",
  archiveLink: "#CardMenu0_0 #Archiveacquisition_MenuItem0",
  archiveModal: "#ArchivePackageModal",
  archiveModaltitle: "#ArchivePackageModalTitle",
  archiveBtn: "#ArchiveButton_OK",
  restorePackage:"#Restorepackagetodraft_MenuItem0"
}
