module.exports = {
  app:"#atat-app",
  title: "title",
  packageNameHeader:"header.v-toolbar div.h3",
  header: "h1.page-header",
  sideBarList: ".global-side-nav-bar .v-list",
  stepperProgressBarTextPrimary: "._stepper-progress-bar .text-primary",
  stepperProgressBarText: "._stepper-progress-bar .text-base",
  progressBar: ".v-progress-linear__determinate",
  completePercentage:".global-side-nav-bar .completed-check[data-substep-complete-percentage]",
  stepAcquisitionText: "#Step_AcquisitionPackageDetails >.step-text",
  stepAcquisitionCircle:"#Step_AcquisitionPackageDetails > .step-circle",
  subStepProjectOverviewTxt:"#SubStep_ProjectOverview > .step-text",
  subStepOrganizationTxt: "#SubStep_Organization > .step-text",
  subStepOrganizationLink:"#SubStep_Organization",
  subStepContactInformationTxt: "#SubStep_ContactInformation > .step-text",
  subStepContactInformationLink: "#SubStep_ContactInformation",
  rightMenuTab: "header ul.navbar-nav",
  portal: "#Portals",
  userAvatar: ".sub-avatar",
  footerLinks:".atat-page-footer .links",
  continueBtn:"#ContinueButton",
  backBtn: "#BackButton span span",
  //Fair Opporunity
  stepFairOppLink:"#Step_FairOpportunityProcess",
  stepFairOppText: "#Step_FairOpportunityProcess .step-text",
  stepFairOppTextCircle: "#Step_FairOpportunityProcess .step-circle",  
  subStepExceptionsLink: "#SubStep_Exceptions",
  subStepExceptionsText: "#SubStep_Exceptions .step-text",
  subStepJustificationLink: "#SubStep_JustificationandApproval",
  subStepJustificationText: "#SubStep_JustificationandApproval .step-text",
  //Financial Details
  stepFinancialDetailsLink:"#Step_FinancialDetails",
  stepFinancialDetailsText: "#Step_FinancialDetails .step-text",
  stepFinancialDetailsCircle: "#Step_FinancialDetails .step-circle",
  subStepRequirementsCostEstimateText: "#SubStep_RequirementsCostEstimate .step-text",
  //Background
  stepBackgroundLink: "#Step_Background",
  stepBackgroundText: "#Step_Background .step-text",
  stepBackgroundCircle: "#Step_Background .step-circle",
  substepCurrentContractLink: "#SubStep_CurrentContract",
  substepCurrentContractText: "#SubStep_CurrentContract .step-text",
  substepCurrentEnvironmentLink: "#SubStep_CurrentEnvironment",
  substepCurrentEnvironmentText: "#SubStep_CurrentEnvironment .step-text",
  stepExceptionToFpLink: "#Step_ExceptiontoFairOpportunity",
  stepExceptionToFpText: "#Step_ExceptiontoFairOpportunity .step-text",
  //Contract Details
  stepContractDetailsLink: "#Step_ContractDetails",
  stepContractDetailsText: "#Step_ContractDetails .step-text",
  subStepPopLink: "#SubStep_PeriodofPerformance",
  subStepPopText: "#SubStep_PeriodofPerformance .step-text",
  subStepCoILink: "#SubStep_ConflictofInterest",
  subStepCoIText: "#SubStep_ConflictofInterest .step-text",
  subStepPPSLink: "#SubStep_PackagingPackingandShipping",
  subStepPPSText: "#SubStep_PackagingPackingandShipping .step-text",
  subStepTrainingLink: "#SubStep_Training",
  subStepTrainingText: "#SubStep_Training .step-text",
  //Government Furnished Euipment
  stepGovFurEquipLink: "#Step_GovernmentFurnishedEquipment",
  stepGovFurEquipText: "#Step_GovernmentFurnishedEquipment .step-text",
  subStepPropDetailsLink: "#SubStep_PropertyDetails",
  subStepPropDetailsText: "#SubStep_PropertyDetails .step-text",
  substepJustificationLink: "#SubStep_Justification",
  substepJustificationText: "#SubStep_Justification  span.step-text",
  //Other Contract Considerations
  stepOCCLink: "#Step_OtherContractConsiderations",
  stepOCCText: "#Step_OtherContractConsiderations .step-text",
  subStepPIILink: "#SubStep_PersonallyIdentifiableInformationPII",
  subStepPIIText: "#SubStep_PersonallyIdentifiableInformationPII .step-text",
  subStepBAALink: "#SubStep_BusinessAssociateAgreementBAA",
  subStepBAAText: "#SubStep_BusinessAssociateAgreementBAA .step-text",
  substepPDOILink: "#SubStep_PublicDisclosureofInformation",
  substepPDOIText: "#SubStep_PublicDisclosureofInformation .step-text",
  substepSection508Link: "#SubStep_Section508Standards",
  substepSection508Text: "#SubStep_Section508Standards .step-text",
  //Evaluation Criteria
  stepEvaluationCriteriaLink: "#Step_EvaluationCriteria",
  stepEvaluationCriteriaText: "#Step_EvaluationCriteria .step-text",
}
