module.exports = {
  app:"#atat-app",
  title: "title",
  packageNameHeader:"header.v-toolbar div.h3",
  header: "h1.page-header",
  sideBarList: ".global-side-nav-bar .v-list",
  stepperProgressBarTextPrimary: "._stepper-progress-bar .text-primary",
  stepperProgressBarText: "._stepper-progress-bar .text-base",
  progressBar: ".v-progress-linear__determinate",
  completePercentage:".global-side-nav-bar .completed-check[data-substep-complete-percentage]",
  stepAcquisitionText: "#Step_AcquisitionPackageDetails >.step-text",
  stepAcquisitionCircle:"#Step_AcquisitionPackageDetails > .step-circle",
  subStepProjectOverviewTxt:"#SubStep_ProjectOverview > .step-text",
  subStepOrganizationTxt: "#SubStep_Organization > .step-text",
  subStepOrganizationLink:"#SubStep_Organization",
  subStepContactInformationTxt: "#SubStep_ContactInformation > .step-text",
  subStepContactInformationLink: "#SubStep_ContactInformation",
  rightMenuTab: "header ul.navbar-nav",
  portal: "#Portals",
  userAvatar: ".sub-avatar",
  footerLinks:".atat-page-footer .links",
  continueBtn:"#ContinueButton",
  backBtn:"#BackButton span span",
  stepFairOppLink:"#Step_FairOpportunityProcess",
  stepFairOppText: "#Step_FairOpportunityProcess .step-text",
  stepFairOppTextCircle: "#Step_FairOpportunityProcess .step-circle",  
  subStepExceptionsLink: "#SubStep_Exceptions",
  subStepExceptionsText: "#SubStep_Exceptions .step-text",
  stepFinancialDetailsLink:"#Step_FinancialDetails",
  stepFinancialDetailsText: "#Step_FinancialDetails .step-text",
  stepFinancialDetailsCircle: "#Step_FinancialDetails .step-circle",  
  stepBackgroundLink: "#Step_Background",
  stepBackgroundText: "#Step_Background .step-text",
  stepBackgroundCircle: "#Step_Background .step-circle",
  substepCurrentContractLink: "#SubStep_CurrentContract",
  substepCurrentContractText: "#SubStep_CurrentContract .step-text",
  substepCurrentEnvironmentLink: "#SubStep_CurrentEnvironment",
  substepCurrentEnvironmentText: "#SubStep_CurrentEnvironment .step-text",
  stepExceptionToFpLink: "#Step_ExceptiontoFairOpportunity",
  stepExceptionToFpText: "#Step_ExceptiontoFairOpportunity .step-text",
  stepContractDetailsLink: "#Step_ContractDetails",
  stepContractDetailsText: "#Step_ContractDetails .step-text",
  subStepPopLink: "#SubStep_PeriodofPerformance",
  subStepPopText: "#SubStep_PeriodofPerformance .step-text",
  subStepRequirementsCostEstimateText: "#SubStep_RequirementsCostEstimate .step-text"
}