module.exports = {
  ditcoLink: ".page-intro ._text-link",
  searchContactWrapper: "#SearchContact_AutoComplete_Wrapper",
  searchContactInput: "#SearchContact",
  searchContactActive: "#SearchContact_AutoComplete_Wrapper" +
    " .menuable__content__active.v-autocomplete__content",
  searchContactNoResult: "#SearchContact_AutoComplete_Wrapper .no-results",
  searchError:"#SearchContact_AutoComplete_Wrapper .field-error",
  searchContactNoResultLink: "a#NoResults_SearchContact",
  searchContactListItems: "#SearchContact_AutoComplete_Wrapper .v-list-item__title",
  selectedContactCard: "#SelectedContactCard",
  selectedContactCardName: "#SelectedContactCard_Name",
  selectedContactCardEmail: "#SelectedContactCard_Email",
  selectedContactCardPhone: "#SelectedContactCard_Phone",
  selectedContactCardOrgName: "#SelectedContactCard_OrgName",
  selectedContactCardMessage: "#SelectedContactCard_Message",
  requestedContactChangeLink: "#RequestContactChange" ,
  removeSelectedContactInfoLink: "#RemoveSelectedContactInfo",
  requestModalTitle: "#AddAgencyModalTitle",
  requestModalMessage: "#AddAgencyModalMessage",
  infoChangeTxtBox: "#InformationChange_text_area",
  sendRequestBtn: "#dialog_ok",
  cancelRequestBtn: "#dialog_cancel",
  contactFormToggle: "#ContactFormToggle",
  contactHeaderTxt: "#ContactInfoHeader",
  contactRoleError:"#ContactAffiliation_radio_group_control .field-error",
  serviceBranchDropdown: "#Branch_dropdown",
  serviceBranchError:"#Branch_dropdown_field_control .field-error",
  serviceBranchDropdownList: "#Branch_dropdown_field_control .v-list",
  contactAffRadioActive: "#ContactAffiliation_radio_group_control .v-item--active",
  contactAffRadioGroupTxt:"#ContactAffiliation_radio_group_control legend",
  rankAutoWrapper: "#Rank_AutoComplete_Wrapper",
  rankAutoCompleteList: "#Rank_AutoComplete_Wrapper .v-list-item__title",
  rankInput: "#Rank",
  rankError:"#Rank_AutoComplete_Wrapper .field-error",
  salutationLabel: "#Salutation_dropdown_field_label",
  salutationDropDownControl: "#Salutation_dropdown_field_control",
  toolTipBtnDodaac: "#TooltipButton_DoDAAC",
  toolTipBtnDodaacCOR: "#TooltipButton_COR_DoDAAC",
  toolTipBtnDodaacACOR: "#TooltipButton_ACOR_DoDAAC",
  toolTipTxtDodaac: "#TooltipText_DoDAAC",
  toolTipTxtDodaacCOR: "#TooltipText_COR_DoDAAC",
  toolTipTxtDodaacACOR: "#TooltipText_ACOR_DoDAAC",
  emailTxtBox: "#EmailAddress_text_field",
  emailError:"#EmailAddress_text_field_control .field-error",
  phoneInputBox: "#PhoneNumber_textField",
  dodaacLabel: "#DoDAAC_text_field_label",
  dodaacTxtBox: "#DoDAAC_text_field",
  dodaacError:"#DoDAAC_text_field_control .field-error",
  accessRadioGroup: "#AccessToEdit_radio_group_control legend",
  accessYesRadioBtn: "#Radio_AccessToEditYes",
  accessNoRadioBtn: "#Radio_AccessToEditNo"
}
