module.exports = {
  contactRoleTxt: "#ContactRole_radio_group_control legend",
  contactRadioBtnActive:"#ContactRole_radio_group_control .v-item--active",
  civilianRadioBtn: "#Radio_Civilian",
  militaryRadioBtn: "#Radio_Military",
  contractorRadioBtn: "#Radio_Contractor",
  serviceBranchControl: "#Branch_dropdown_field_control",
  serviceBranchDropDownIcon: "#Branch_dropdown_field_control .v-input__append-inner > .v-icon",
  serviceBranchAirForce: "#Branch_DropdownListItem_USAirForce",
  serviceBranchArmy: "#Branch_DropdownListItem_USArmy",
  serviceBranchCoastGuard: "#Branch_DropdownListItem_USCoastGuard",
  serviceBranchMarineCorps:"#Branch_DropdownListItem_USMarineCorps",
  serviceDropDownList: "#Branch_dropdown_field_control .v-list",
  salutationDropDownLabel: "#Salutation_dropdown_field_label",
  salutationDropDownIcon: "#Salutation_dropdown_field_control .v-input__append-inner > .v-icon",
  salutationDropDownList:"#Salutation_dropdown_field_control .v-list-item",
  salutationDropdownListItemMr:"#Salutation_DropdownListItem_Mr",
  salutationDropdownListItemMrs: "#Salutation_DropdownListItem_Mrs",
  salutationDropdownListItemMiss: "#Salutation_DropdownListItem_Miss",
  salutationDropdownListItemMs: "#Salutation_DropdownListItem_Ms",
  salutationDropdownListItemDr: "#Salutation_DropdownListItem_Dr",
  rankInput: "#Rank",
  rankAutoCompleteWrapper:"#Rank_AutoComplete_Wrapper",
  rankAutoCompleteList: "#Rank_AutoComplete_Wrapper .v-list-item__title",
  gradeAutoCompleteWrapper:"#ContactGrade_AutoComplete_Wrapper",
  gradeLabel: "#ContactGrade_AutoComplete_Wrapper .mb-2.d-block",
  gradeDropDownIcon: "#ContactGrade_AutoComplete_Wrapper .v-input__icon.v-input__icon--append",
  gradeInput: "#ContactGrade_AutoComplete_Wrapper",
  gradeDropDownList:"#ContactGrade_AutoComplete_Wrapper .v-list-item__title",
  fNameLabel:"#FirstName_text_field_label",
  lNameLabel: "#LastName_text_field_label",
  mNameLabel: "#MiddleName_text_field_label",
  emailLabel: "#ContactEmail_text_field_label",
  emailMessage: "#ContactEmail_text_field_control .help-text.mt-2",
  phoneNumberLabel: "#ContactPhone_TextFieldLabel",
  phoneControlIcon: "#PhoneControl .v-input__slot div > .v-icon",
  phoneDropdown: "#DropdownTextField",
  countryListItems:"#PhoneControl ._country-list.v-list-item",
  fNameTxtBox:"#FirstName_text_field",
  lNameTxtBox: "#LastName_text_field",
  mNameTxtBox: "#MiddleName_text_field",
  emailTxtBox: "#ContactEmail_text_field",
  phoneInputBox:"#ContactPhone_textField"
}