module.exports = {
   // Let’s gather some details about the duration of your task order 
  popLearnMoreLink: "#PoPLearnMore",
  popText: "p.mb-10",
  popLengthLabelText: "div.mb-4._semibold",
  baseRow:"#BaseRow.d-flex.mb-5",
  baseLabelText: "#BaseRow .d-flex",
  baseInputTxtBox: "#Base_text_field",
  baseDropdownIcon: "#Base_dropdown_field_control .v-input__control .v-input__append-inner",
  baseDropdownList: "#Base_dropdown_field_control .v-list",
  baseDropdownYear: "#Base_DropdownListItem_Year",
  baseDropdownMonth: "#Base_DropdownListItem_Months",
  baseDropdownWeek: "#Base_DropdownListItem_Weeks",
  baseDropdownDays:"#Base_DropdownListItem_Days",
  basebutton: "#BaseButtons",
  baseDuplicateButton:"button.mr-1.v-btn",
  baseDeleteButton: "#BaseRowbutton.v-btn.v-btn",
  addOptionLink: "#addOptionPeriodButton",
  optionRow:"#Option1Row.d-flex.mb-5",
  optionalTextBox: "#Option1_text_field",
  optionDropdownIcon: "#Option1_dropdown_field_control .v-input__control .v-input__append-inner",
  optionDropdownList: "#Option1_dropdown_field_control .v-list",
  optionDropdownYear: "#Option1_DropdownListItem_Year",
  optionDropdownMonth: "#Option1_DropdownListItem_Months",
  optionDropdownWeek: "#Option1_DropdownListItem_Weeks",
  optioneDropdownDays:"#Option1_DropdownListItem_Days",
  errorMessageText: ".field-error.ml-2",
  //Do you want to request a PoP start date?
  popStartDateYesRadioOption: "#Radio_YesStartDate",
  popStartDateNoRadioOption: "#Radio_NoStartDate",
  requestedStartDate: "p.mb-2",
  requestedStartDropdownIcon: "#RequestDateOption_dropdown_field_control .v-input__control .v-input__append-inner",
  requestedStartDropdownList:"#RequestDateOption_dropdown_field_control .v-list",
  requestedStartDateNosoonerthan: "#RequestDateOption_DropdownListItem_Nosoonerthan",
  requestedStartDateNotlaterthan:"#RequestDateOption_DropdownListItem_Notlaterthan",
  calendarIcon: "#RequestDatePickerDatePickerButtonIcon",
  navigateCalendar: ".v-date-picker-header i",
  navigateNextMonth: "button[aria-label='Next month']",
  selectDate:".v-date-picker-table button:not(.v-btn--disabled)",
  recurringReqText: "p.mb-10",
  yesRadioOption: "#Radio_YesRecurring",
  noRadioOption: "#Radio_NoRecurring",
  activeRadioOption:"#RecurringOptions_radio_group_control .v-item--active",
  popRadioGroup:"#PoPStartDate_radio_group_control"
  }