module.exports = {
  // Let’s gather some details about the duration of your task order 
  popLearnMoreLink: "#PopLearnMore",
  popText: "p.mb-10",
  popLengthLabelText: "div.mb-4._semibold",
  mainWrap:".v-main__wrap",
  baseRow:"#BaseRow",
  baseLabelText: "#BaseRow .duration",
  baseInputTxtBox: "#BaseDuration_text_field",
  baseDropdownIcon: "#BaseDropdown_dropdown_field_control .v-input__control .v-input__append-inner",
  baseDropdownList: "#BaseDropdown_dropdown_field_control  .v-list",
  baseDropdownYear: "#Base_DropdownListItem_Year",
  baseDropdownMonth: "#BaseDropdown_DropdownListItem_Months",
  baseDropdownWeek: "#Base_DropdownListItem_Weeks",
  baseDropdownDays:"#Base_DropdownListItem_Days",
  basebutton: "#BaseButtons",
  baseDuplicateButton:"#BaseCopy",
  baseDeleteButton: "#BaseDelete",
  addOptionLink:"#AddOptionPeriodButton",
  optionRow:"#Option1Row",
  optionalTextBox: "#Option1Duration_text_field",
  optionDropdownIcon: "#Option1_dropdown_field_control .v-input__control .v-input__append-inner",
  optionDropdownList: "#Option1_dropdown_field_control .v-list",
  optionDropdownYear: "#Option1_DropdownListItem_Year",
  optionDropdownMonth: "#Option1_DropdownListItem_Months",
  optionDropdownWeek: "#Option1_DropdownListItem_Weeks",
  optioneDropdownDays: "#Option1_DropdownListItem_Days",
  optionOneDropdownSelected:"#Option1Dropdown_dropdown_field_control .v-select__selection--comma",
  errorMessageText: ".field-error.ml-2",
  optionDeleteButton: "#Option1Delete",
  sourceItem: "#Option2Row",
  targetItem: "#BaseRow",
  optionalTwoTextBox: "#Option2Duration_text_field",
  
  //Do you want to request a PoP start date?
  popStartDateYesRadioOption: "#Radio_YesStartDate",
  popStartDateNoRadioOption: "#Radio_NoStartDate",
  requestedStartDate: "p.mb-2",
  requestedStartDropdownIcon: "#RequestDateOption_dropdown_field_control" +
      " .v-input__control .v-input__append-inner",
  requestedStartDropdownList:"#RequestDateOption_dropdown_field_control .v-list",
  requestedStartDateNosoonerthan: "#RequestDateOption_DropdownListItem_Nosoonerthan",
  requestedStartDateNotlaterthan: "#RequestDateOption_DropdownListItem_Notlaterthan",
  warningTextMessage: "._atat-alert .mb-0",
  requestDatePicker: "#RequestDatePickerDatePickerTextField",
  requestDatePickerError:"#RequestDatePickerDatePickerContainer .field-error",
  calendarIcon: "#RequestDatePickerDatePickerButtonIcon",
  navigateCalendar: ".v-date-picker-header i",
  navigateNextMonth: "button[aria-label='Next month']",
  selectDate: ".v-date-picker-table button:not(.v-btn--disabled)",
  popStartRadioError:"#PoPStartDate_radio_group_control .field-error",

  //will this be a future recurring requirement?
  recurringReqText: "p.mb-10",
  yesRadioOption: "#Radio_YesRecurring",
  noRadioOption: "#Radio_NoRecurring",
  activeRadioOption:"#RecurringOptions_radio_group_control .v-item--active",
  popRadioGroup: "#PoPStartDate_radio_group_control",
  futureRecurringRadioError: "#RecurringOptions_radio_group_control .field-error",
  
  //which Contract type applies to this acquistion?
  introPText: "#IntroP",
  farLink: "._text-link",
  selectMessageText: "#SelectMessage",
  ffpCheckBox: "#Checkbox_FFPCheckbox",
  tmCheckBox: "#Checkbox_TMCheckbox",
  tmTextFieldLabel:"#JustificationForTM_text_field_label",
  tmTextFieldInputBox: "#JustificationForTM_text_area",
  tmLearnMoreLink: "#JustificationLearnMore",
  
  //What classification level(s) will be required for your cloud resources and /or services?
  selectMess: "#SelectMessage",
  classCheckBoxes: "#ClassificationLevelCheckboxes",
  level2: "#Checkbox_IL2",
  level4: "#Checkbox_IL4",
  level5: "#Checkbox_IL5",
  level6: "#Checkbox_IL6",
  errorClassCheckBox: "#ClassificationLevelCheckboxes .field-error",
  alertMessage: "#ClassificationRequirementsAlert p",
}
