module.exports = {
//Let’s work on an evaluation plan for your requirement
  introDescription: ".page-intro",  
  evalPlanOptionsLabel: "#EvalPlanOptions_radio_group_control .form-field-label ",  
  evalPlanRadioActiveBtn: "#EvalPlanOptions_radio_group_control .v-item--active",
  noTechProposal: "#Radio_NoTechProposal",
  techProposal: "#Radio_TechProposal",
  setLumpSum: "#Radio_SetLumpSum",
  equalLumpSum: "#Radio_EqualSetLumpSum",
  methodSelection: "#MethodSelectionSection",
  methodSelectionSecLabel:"#MethodSelectionSection legend",
  lptaRadioBtn: "#MethodSelectionSection #Radio_LPTA",
  bvtoRadioBtn: "#MethodSelectionSection #Radio_BVTO",
  bestUseRadioBtn: "#Radio_BestUse",
  lowestRiskRadioBtn: "#Radio_LowestRisk",
  learnMoreLink: "#LearnMore",  
  methodSecActiveBtn: "#MethodSelection_radio_group_control .v-item--active",
  techPropAlertSubHeader:"#Callout #Subhead",
  //no Tech Proposal review Compliance Standads
  customStandardsRadioGroupLabel: "#CustomStandards_radio_group_control .form-field-label",
  customRadioYesBtn: "#CustomStandards_radio_group_control #Radio_Yes",
  customRadioNoBtn: "#CustomStandards_radio_group_control #Radio_No",
  customRadioGroupError:"#CustomStandards_radio_group_control .field-error",
  customRadioActiveBtn: "#CustomStandards_radio_group_control  .v-item--active",
  customSpecSection: "#CustomSpecEntry",
  customSpec0Control:"#CustomSpec0_text_field_control",
  custom0SpecTextbox: "#CustomSpec0_text_field",
  custom0DeleteBtn:"#DeleteCustomSpec_0",
  custom1SpecControl: "#CustomSpec0_text_field_control",
  custom1SpecTextbox: "#CustomSpec1_text_field",
  custom1Spec: "#CustomSpecEntry .px-4",
  custom1DeleteBtn:"#DeleteCustomSpec_1",
  addAnotherCustomCS: "#AddCustomSpecButton",
  //Now let’s review assessment criteria required for white papers
  otherAssessmentareasLabel: "#OtherAssessmentAreasLabel",
  checkboxesLabel: "._checkboxes input[type=checkbox]",
  riskToGovCheckBox: "#Checkbox_RiskToGovt",
  automationCapabilityCheckBox: "#Checkbox_AutomationCapability",
  customAssessmentCheckBox: "#Checkbox_CustomAssessmentOption",
  noOtherBtn: "#NoOtherAssessmentAreas",
  //What differentiator(s) should be used to distinguish between technical proposals?
  levelComplexityCheckbox: "#Checkbox_LevelOfComplexity",
  capGain:"#Checkbox_CapabilityGained",
  differentitorsError: "#DifferentiatorOptions  .field-error",
  otherCheckboxOption: "#Checkbox_CustomDifferentiators",
  customDifferentiatorSection: "#CustomDifferentiatorEntry",
  custom0SpecTextboxError: "#CustomSpec0_text_field_control .field-error",
  customDifferentiator1Spec:"#CustomDifferentiatorEntry .px-4"
}