module.exports = {
  financialSideStepLink:"#Step_FinancialDetails",
  surgeCapabilitiesTxt: "._callout h2",
  contractPriceTxt:"p.mt-8.mb-2",
  contractPricePercentageTxtBox: "#ContractPricePercentage_text_field",
  contractPriceControl:"#ContractPricePercentage_text_field_control",
  contractPriceError: "#ContractPricePercentage_text_field_control .field-error",
  
  //Funding plan
  intrpText: "#IntroP",
  learnFundingLink: "#LearnMoreFunding",
  slideoutPanel: "._slideout-panel",
  panelTitle: "#PanelTitle",
  panelClose: "#PanelCloser",
  panelMainLabelText: "#PanelWrap h2",
  panelNextLabelText: "#PanelWrap h3",
  panelFARLink:"#FARLink",
  fsfRadioBtn: "#Radio_FSFCheckbox",
  fsfCardLabel:":nth-child(1) > .v-label",
  miprRadioBtn: "#Radio_MIPRCheckbox",
  miprCardLabel:":nth-child(2) > .v-label",
  fundingRadioActive: "#FundingTypesRadioGroup_radio_group_control .v-item--active",
  fundingRadioError: "#FundingTypesRadioGroup_radio_group_control  .field-error",
  aboutFRLink: "#Button_AboutMissingFundingRequest",
  aboutRequestMessage: "#Content_AboutMissingFundingRequest",
  ginvoiceLink: "#LearnMoreGInvoicing",

  //Did tou use G-Invoicing for your funding request?
  ginvoiceYesRadioBtn: "#",
  ginvoiceNoRadioBtn: "#",
  gInvoiceActiveRadioOption: "#GInvoicingOptions_radio_group_control .v-item--active",
  gInvoiceErrorRadioOption: "#GInvoicingOptions_radio_group_control  .field-error",
  
  //Let's Gather Info about your MIPR
  miprTextLabel: "#MIPRNumber_text_field_label",
  miprTooltipBtn: "#TooltipButton_MIPRNumber",
  miprTooltipText: "#TooltipText_MIPRNumber",
  miprTextbox: "#MIPRNumber_text_field",
  UploadLabel:"h3.mb-5",
  form: "form.v-form",
  fileUploadSection: ".atat-file-upload",
  uploadLink: "#BrowseToUpload",
  fundingfileupload: "#FundingPlanFileUpload",
  fundingfileuploadError: "form.v-form .field-error",
  uploadedFile0Link: "#FileLink00",
  uploadedFile0RemoveBtn: "#RemoveFile00",
  
  //severability and incremental funding
  iFundIntroTxt:"p.mb-10",
  iFundYesRadio: "#Radio_Yes",
  iFundNoRadio: "#Radio_No",
  iFundRadioerror: "#IncrementallyFundOptions_radio_group_control .field-error",
  iFundActiveBtn: "#IncrementallyFundOptions_radio_group_control .v-item--active",
  IFPFAQ1Link: "#Button_IFPFAQ1",
  IFPFAQ1ContentText:"#Content_IFPFAQ1",
  IFPFAQ2Link: "#Button_IFPFAQ2",
  IFPFAQ2ContentText: "#Content_IFPFAQ2",
  alertWarning: "#IFPRequestPageAlert",
  alertWarningHeader: "#IFPRequestPageAlert h3",
  alertInfoMessage: "#AlertInfo",
  updatePOPLink: "#PoPLink",
  updateRCELink: "#CostEstimateLink",
  contractDetailsLink:"#AlertLink"
}
