module.exports = {
  financialSideStepLink:"#Step_FinancialDetails",
  surgeCapabilitiesTxt: "._callout h2",
  contractPriceTxt:"p.mt-8.mb-2",
  contractPricePercentageTxtBox: "#ContractPricePercentage_text_field",
  contractPriceControl:"#ContractPricePercentage_text_field_control",
  contractPriceError: "#ContractPricePercentage_text_field_control .field-error",
  
  //Funding plan
  intrpText: "#IntroP",
  learnFundingLink: "#LearnMoreFunding",
  slideoutPanel: "._slideout-panel",
  panelTitle: "#PanelTitle",
  panelClose: "#PanelCloser",
  panelMainLabelText: "#PanelWrap h2",
  panelNextLabelText: "#PanelWrap h3",
  panelFARLink:"#FARLink",
  fsfRadioBtn: "#Radio_FSFCheckbox",
  fsfCardLabel:"label[for=Radio_FSFCheckbox]",
  miprRadioBtn: "#Radio_MIPRCheckbox",
  miprCardLabel:"label[for=Radio_MIPRCheckbox]",
  fundingRadioActive: "#FundingTypesRadioGroup_radio_group_control .v-item--active",
  fundingRadioError: "#FundingTypesRadioGroup_radio_group_control  .field-error",
  aboutFRLink: "#Button_AboutMissingFundingRequest",
  aboutRequestMessage: "#Content_AboutMissingFundingRequest",
  ginvoiceLink: "#LearnMoreGInvoicing",
  bureauLink: "#BFSLink",
  ginvoiceLoginLink:"#GInvoicingLoginLink",

  //Did you use G-Invoicing for your funding request?
  ginvoiceYesRadioBtn: "#Radio_Yes",
  ginvoiceNoRadioBtn: "#Radio_No",
  gInvoiceActiveRadioOption: "#GInvoicingOptions_radio_group_control .v-item--active",
  gInvoiceErrorRadioOption: "#GInvoicingOptions_radio_group_control  .field-error",
  yesLabel: "#GInvoicingOptions_radio_group_control label[for=Radio_Yes]",
  noLabel: "#GInvoicingOptions_radio_group_control label[for=Radio_No]",
  gInvoiceOrderNo: "#OrderNumber_Label",
  orderNoSearchInput: "#OrderNumber_SearchInput",
  orderNosearchAlertSucess: "#OrderNumber_SearchAlertSuccess",
  orderNosearchError: "#SearchWrapper .field-error",
  orderNoSearchBtn: "#OrderNumber_SearchButton",
  
  //Let's Gather Info about your MIPR
  miprTextLabel: "#MIPRNumber_text_field_label",
  miprTooltipBtn: "#TooltipButton_MIPRNumber",
  miprTooltipText: "#TooltipText_MIPRNumber",
  miprTextbox: "#MIPRNumber_text_field",
  miprTextboxError:"#MIPRNumber_text_field_control  .field-error",
  UploadLabel:"h3.mb-5",
  form: "form.v-form",
  fileUploadSection: ".atat-file-upload",
  uploadLink: "#BrowseToUpload",
  fundingfileupload: "#FundingPlanFileUpload",
  fundingfileuploadError: ".file-upload-validation-messages",
  uploadedFile0Link: "#FileLink00",
  uploadedFile0RemoveBtn: "#RemoveFile00",

  //Let's gather info about your 7600A and 7600B
  gtcNoLabel: "#GeneralTermsAndConditions_text_field_label",
  gtcTooltipBtn: "#TooltipButton_GeneralTermsAndConditions",
  gtcTooltipText: "#TooltipText_GeneralTermsAndConditions",
  gtcNoInput: "#GeneralTermsAndConditions_text_field",
  gtcNoError: "#GeneralTermsAndConditions_text_field_control  .field-error",
  orderNoLabel: "#OrderNumber_text_field_label",
  orderNoTooltipBtn: "#TooltipButton_OrderNumber",
  orderNoTooltipText: "#TooltipText_OrderNumber",
  orderNoInput: "#OrderNumber_text_field",
  orderNoError: "#OrderNumber_text_field_control  .field-error",
  uploadTitle: ".h4",
  browserToUploadLink: "#BrowseToUpload",
  uploadFileName0: "#File00",
  uploadFileName1: "#File01",
  uploadAlertText:"#UPload7600Alert",
  
  //severability and incremental funding
  iFundIntroTxt:"p.mb-10",
  iFundYesRadio: "#Radio_Yes",
  iFundNoRadio: "#Radio_No",
  iFundRadioerror: "#IncrementallyFundOptions_radio_group_control .field-error",
  iFundActiveBtn: "#IncrementallyFundOptions_radio_group_control .v-item--active",
  IFPFAQ1Link: "#Button_IFPFAQ1",
  IFPFAQ1ContentText:"#Content_IFPFAQ1",
  IFPFAQ2Link: "#Button_IFPFAQ2",
  IFPFAQ2ContentText: "#Content_IFPFAQ2",
  alertWarning: "#IFPRequestPageAlert",
  alertWarningHeader: "#IFPRequestPageAlert h3",
  alertInfoMessage: "#AlertInfo",
  updatePOPLink: "#PoPLink",
  updateRCELink: "#CostEstimateLink",
  contractDetailsLink: "#AlertLink",
  popUnder9monthsText: "#PoPUnder9Months",
  linkToPoP: "#LinkToPoP",
  
  //Let's create an incremental funding plan for your base period
  initialFILabel: "label", 
  initalFITextbox: "#InitialAmount_text_field",
  initalFIError: "#InitialIncrementError",
  incrementalPeriod0Dropdown: "#IncrementPeriod0_dropdown",
  incrementalPeriod0DropdownIcon: "#IncrementPeriod0_dropdown_field_control" +
    " .v-input__append-inner > .v-icon",
  incrementalPeriod0DropdownList:"#IncrementPeriod0_dropdown_field_control .v-list-item",
  incrementalPeriod0AmountTextbox:"#Amount0_text_field",  
  incrementalPeriod0Error: "#Increment0 .field-error",
  incrementalPeriod1:"#IncrementPeriod1_dropdown_field_control",
  deleteBtn0: "#DeleteIncrement0",
  deleteBtn1:"#DeleteIncrement1",
  addIncrementalbtn: "#AddIncrementButton",
  periodLength: "#PeriodLength",
  totalCostEst:"#TotalCostEstimate",
  basePeriodValue: ".pa-6 .h3",
  basePeriodText: ".pa-6 p.mb-0",
  amountRemaining:"#AmountRemaining",
  total: "#TotalAmount_text_field",
  
  //Tell us about your financial POC
  contactRoleTxt: "#ContactAffiliation_radio_group_control legend",
  contactRadioBtnActive: "#ContactAffiliation_radio_group_control .v-item--active", 
  emailLabel: "#EmailAddress_text_field_label",
  emailMessage: "#EmailAddress_text_field_control .help-text.mt-2",
  emailTextbox:"#EmailAddress_text_field",
  phoneNumberLabel: "#PhoneNumber_TextFieldLabel",
  phoneInputBox:"#PhoneNumber_textField"
}
