module.exports = {
  welcomeBarText: "._welcome-bar h1",
  startAcqWelcome:"._welcome-bar button",
  helpfulResources: "._welcome-bar #HelpfulResourcesButton",
  startSectionHeader:"._new-user-cards h2.h1",
  startAcqPackBtn: "#StartBuildingPackageCard #StartNewAcquisition",
  sectionPrepareHeader:"#SectionPreparePackage h1",
  sectionPrepareStartBtn:"#SectionPreparePackage #StartNewAcquisitionButton",
  startAcqLearnMoreBtn:"#StartBuildingPackageCard #LearnMoreBuilding",
  existJWTCCToSection: "#StartBuildingPackageCard h2.h1",
  existJWTCCToSectionLearnMore: "#LearnMoreTOSearch",
  prepAcqPackHeader: "#SectionPreparePackage h1",
  prepAcqPackStartBtn: "#SectionPreparePackage #StartNewAcquisitionButton",
  provisionCloudTitle: "#SectionProvisionResources h1",
  provisionBtn: "#ProvisionResourcesButton",
  helpResourceCards: "#HelpfulResourcesCards",
  helpResourceCardsHeaders: ".pa-6 h3",
  helpButtons: ".pa-6 button",
  alert: "#Alert",
  acqPackageaccordion: "#PackagesAccordion",
  acqCard0: "#PackagesAccordion #Package0",
  acqPackage0:"#Portfolio0"
}
