module.exports = {

  //conflict of Interest
  coiBodyCopyTxt: "p.mb-10",
  coiLearnMoreLink: "#CoILearnMore",
  coiYesRadioOption: "#COIOptions_radio_group_control #Radio_Yes",
  coiNoRadioOption: "#COIOptions_radio_group_control #Radio_No",
  coiActiveRadioOption:"#COIOptions_radio_group_control .v-item--active",
  coiRadioError:"#COIOptions_radio_group_control .field-error",
  explanationTxtFieldControl:"#Explanation_text_field_control",
  explanationLabelText: "#Explanation_text_field_label",
  explanationTextBox: "#Explanation_text_area",
  explanationTextError:"#Explanation_text_field_control .field-error",
  coiLearnDrawer: "#SlideoutPanel",
  coiLMDLabel:"._slideout-panel h2",
  coiLMDTitleText: "#PanelTitle",
  coiLMDClose: "#PanelCloser",
  coiFARUrl: "#FAR9502Link ._external-link",
  coiLMDBoldText: "._slideout-panel h3",
  
  //Packaging,Packing and Shipping
  introText: "#IntroP",
  selectMessageLabel: "#SelectMessage",
  contractorProviderCheckBox: "#Checkbox_ContractorProvided",
  contractorProviderLabelTxt:"#PackagingEtcCheckboxes label",
  otherCheckBox: "#Checkbox_Other",
  noneCheckBox: "#Checkbox_NoneApply",
  otherTextBox:"#OTHER_text_area",
  otherTxtError: "#OTHER_text_field_control .field-error",
  checkBoxError: "#PackagingEtcCheckboxes .field-error",
  ppsCB:"#PackagingEtcCheckboxes input[type=checkbox]",
  checkBoxActive:"#PackagingEtcCheckboxes  .v-input--is-label-active",
  ppsCheckedCB:"#PackagingEtcCheckboxes input[type=checkbox]:checked",

   //travel
  noTravelMessage:"#NoTravelMessage",
  addTrip:"#AddInstance",
  travelDialogTitle:"#travelFormDialogTitle",
  tablewrapper:".v-data-table__wrapper",
  travelDialog:"#travelFormDialog",
  btnClassDisabled:"v-btn--disabled",
  btnClassenabled:"v-btn--is-elevated",
  tripLocTxtField:"#TripLocation_text_field",
  durationTxtField:"#Duration_text_field",
  noOfTravlers:"#NumberOfTravelers_text_field",
  noOfTrips:"#NumberOfTrips_text_field",
  cbBasePeriod:"#Checkbox_BaseDisabled",
  modalAddBtn:"#AddTrip",
  firstRow:"table > tbody > tr:nth-child(1) > td",
  editOne:"#EditButton_1",
  deleteOne:"#DeleteButton_1",
  copyOne:"#CopyButton_1",
  copyTwo:"#CopyButton_2",
  editTwo:"#EditButton_2",
  deleteTwo:"#DeleteButton_2",
  deleteModal:"#DeleteInstanceModal",
  deleteModalTitle:"#DeleteInstanceModalTitle",
  modalDeleteBtn:"#DeleteTrip",
  dontNeedTravel:"#DontNeedTravel",  

}
