module.exports = {
  //PII
  blueInfoMessageText:"._atat-alert",
  piiRadioOptionText: "#PIIOptions_radio_group_control legend",
  piiRadioOtionActive:"#PIIOptions_radio_group_control .v-item--active",
  yesPIIRadioOption: "#Radio_YesPII",
  noPIIRadioOption: "#Radio_NoPII",
  piiLink: "#Button_PIIFAQ",
  piiFAQText: "#Content_PIIFAQ p.mb-4",
  patLink: "#PrivacyActLink1",
  paLink: "#PrivacyActLink2",
  moreInfoLink: "#PrivacyActLink3",
  //PII-Tell Us More about your system of records
  systemLabel: "#SystemName_text_field_label",
  systemNameTextBox: "#SystemName_text_field",
  operationPerformedLabel: "#OperationToBePerformed_text_field_label",
  operationPerformedTextBox:"#OperationToBePerformed_text_area",  
  //BAA
  baaLabelText: "._atat-alert h2",
  phiTextMessage: "._atat-alert._callout",
  learnMoreBAALink: "#LearnMoreBAA",
  baaRadioOptionText: "#BAARadioOptions_radio_group_control legend",
  baaRadioOptionActive: "#BAAOptions_radio_group_control .v-item--active",
  yesBAARadioOption: "#Radio_YesBAA",
  noBAARadioOption: "#Radio_NoBAA",
  aboutBALink: "#Button_AboutBusinessAssociates",
  contentAboutBA: "#Content_AboutBusinessAssociates",
  moreInfoBAALink: "a._text-link._external-link",
  infoAlert: "._atat-alert._info-alert p",
  //FOIA
  foiaYesOption: "#Radio_Yes",
  foiaNoOption: "#Radio_No",
  foiaLearnLink: "#FOIALearnMore",
  foiaLearnDrawer: ".v-navigation-drawer__content",
  learnMoreDrawerLabel: "#PanelTitle",
  learnMoreHeaderTxt: "._slideout-panel h2",
  learnMoreDrawerClose: "#PanelCloser",
  learnMoreFOIAUrl: "._text-link",
  foiaFAQLink: "#Button_FOIAFAQ",
  foiaFAQText:"#Content_FOIAFAQ",    
  //508 standards
  introText: "#IntroP",
  blueAlertLabel: "._atat-alert h2",
  scrollBar: "div._atat-alert.mb-10._callout._scrollable.py-0.pr-0",
  secton508Text: "#Section508RadioGroup_radio_group_control legend",
  sectionYesRadio: "#Radio_Yes",
  sectionNoRadio: "#Radio_No",
  about508Link:"#Button_AboutBusinessAssociates"
}
