module.exports = {
  agencyLabel: "#Agency_AutoComplete_Wrapper label",
  agencyDropDownIcon: "#Agency_AutoComplete_Wrapper" +
    " .v-input__icon.v-input__icon--append",
  agencyInput: "#Agency",
  agencyAutoListItems: "#Agency_AutoComplete_Wrapper .v-list-item__title",
  agencyError:"#Agency_AutoComplete_Wrapper .field-error",
  sectionOneHeaderText: "#Section1 h2.form-section-heading",
  orgNameControl: "#OrgName_text_field_control",
  orgNameTxtLabel: "#OrgName_text_field_label",
  orgNameTxtBox: "#OrgName_text_field",
  orgNameError:"#OrgName_text_field_control .field-error",
  disaOrgAutoComplete:"#DisaOrg_AutoComplete_Wrapper",
  disaDropDownLabel: "#DisaOrg_AutoComplete_Wrapper .mb-2.d-block",
  disaOrgInput: "#DisaOrg",
  disaAutoComplete: "#DisaOrg_AutoComplete_Wrapper .v-list-item__title",
  disaDropdownError:"#DisaOrg_AutoComplete_Wrapper .field-error",
  activityAddressCodeLabel: "#DoDAAC_text_field_label",
  activityAddressCodeTxtBox: "#DoDAAC_text_field",
  activityAddressCodeError:"#DoDAAC_text_field_control .field-error",
  sectionTwoHeaderText:"#Section2 h2.form-section-heading",
  addressTypeRadioGroup: "#AddressType_radio_group_control",
  addressTypeRadioActive: "#AddressType_radio_group_control .v-item--active",
  usaRadioBtn: "#Radio_USAddress",
  militaryradioBtn: "#Radio_MilitaryAddress",
  foreignradioBtn: "#Radio_ForeignAddress",
  streetLabel: "#StreetAddress_text_field_label",
  unitLabel: "#UnitSuite_text_field_label",
  cityLabel: "#City_text_field_label",
  stateLabel: "#State_AutoComplete_Wrapper label",
  apoFpoDropDownLabel: "#APO_FPO_DPO_dropdown_field_label",
  apoFpoDropDown:"#APO_FPO_DPO_dropdown",
  apoFpoDropDownListItemsArmy: "#APO_FPO_DPO_DropdownListItem_ArmyPostOfficeAPO",
  apoFpoDropDownListItemsFleet:"#APO_FPO_DPO_DropdownListItem_FleetPostOfficeFPO",
  stateCodeDropDownLabel: "#StateCode_dropdown_field_label",
  stateCodeDropDown: "#StateCode_dropdown",
  stateCodeAmerica: "#StateCode_DropdownListItem_AAArmedForcesAmericas",  
  stateCodeEurope: "#StateCode_DropdownListItem_AEArmedForcesEurope",
  stateCodePacific:"#StateCode_DropdownListItem_APArmedForcesPacific",
  stateProvinceLabel: "#StateProvince_text_field_control",
  stateProvinceTxtBox:"#StateProvince_text_field",
  zipCodeLabel: "#ZIPCode_text_field_label",
  countryLabel:"#Country_AutoComplete_Wrapper .mb-2.d-block",
  streetTxtBox: "#StreetAddress_text_field",
  unitTxtBox: "#UnitSuite_text_field",
  cityTxtBox: "#City_text_field",
  stateTxtBox: "#State",
  postalCodeLabel: "#PostalCode_text_field_label",
  postalCodeTxtBox:"#PostalCode_text_field",
  stateAutoCompleteList: "#State_AutoComplete_Wrapper .v-list-item__title",
  countryInput: "#Country",
  countryListItems:"#Country_AutoComplete_Wrapper .v-list-item__title ",
  zipCodeTxtBox: "#ZIPCode_text_field",
  requestModalTitle: "#AddAgencyModalTitle",
  requestAgencyLink: "#RequestAgencyAdded",
  agencyOrgNameTxtLabel: "#AgencyOrgName_text_field_label",
  streetError: "#StreetAddress_text_field_control .field-error",
  cityError: "#City_text_field_control .field-error",
  stateError: "#State_AutoComplete_Wrapper .field-error",
  zipError: "#ZIPCode_text_field_control .field-error",
  apoFpoDropDownError: "#APO_FPO_DPO_dropdown_field_control .field-error",
  aaAEError: "#StateCode_dropdown_field_control .field-error",
  stateProvinceError: "#StateProvince_text_field_control .field-error",
  postalCodeError: "#PostalCode_text_field_control .field-error",
  countryError:"#Country_AutoComplete_Wrapper .field-error"
}
