module.exports = {
  introPText: "p.mb-10",
  learnMoreLink: "p.mb-10 a",
  singleClassText:"#SingleClass",
  categoryAlertheading: "#CategoryPageAlert h3",
  categoryAlertInfoTxt: "p#AlertInfo",
  xaasLabelText: "#XaaSLabel",
  xaasCheckboxes: "#XaaSCheckboxes",
  cloudSupportCheckboxes: "#CloudSupportCheckboxes",
  cloudSupportLabelText: "#CloudSupportLabel",
  computeCheckBox: "#Checkbox_COMPUTE",
  devtoolsCheckBox: "#Checkbox_DEVELOPERTOOLS",
  appCheckBox: "#Checkbox_APPLICATIONS",
  machLearnCheckBox: "#Checkbox_MACHINELEARNING",
  networkCheckBox: "#Checkbox_NETWORKING",
  securityCheckBox: "#Checkbox_SECURITY",
  storageCheckBox: "#Checkbox_DATABASE",
  teCheckBox: "#Checkbox_EDGECOMPUTING",
  iotCheckBox: "#Checkbox_IOT",
  generalCheckBox: "#Checkbox_GENERALXAAS",
  xaasNoneCheckBox: "#Checkbox_XaaSNoneApply",
  advisoryCheckBox: "#Checkbox_ADVISORY",
  trainingCheckBox: "#Checkbox_TRAINING",
  xassCheckbBoxError: "#XaaSCheckboxes .field-error",
  cloudSupportCheckboxError: "#CloudSupportCheckboxes .field-error",
  dontneedBtn: "#DontNeedResources",

  //Let's start by gathering your Compute requirements
  subAlertMessage:"#SubtleAlertMessage",
  formSectionOneHeader:"#FormSection1Heading",
  environmentLabel: "#EnvironmnetType_radio_group_control .mr-2",
  envDevTesting: "#Radio_DevTesting",
  envPrepodStage: "#Radio_PreProdStaging",
  envProd: "#Radio_Production",  
  regionGroup:"#Regions input[type=checkbox]",
  regionCheckboxLabel: ".font-weight-500",
  eastCheckbox: "#Checkbox_CONUSEast",
  centralCheckBox: "#Checkbox_CONUSCentral",
  westCheckbox: "#Checkbox_CONUSWest",
  oconusCheckbox:"#Checkbox_OCONUS",
  regionTooltipBtn: "#TooltipButton_Region",
  regionTooltipText: "#TooltipText_Region",
  classLevelRadioGroup:"#ClassificationLevel_radio_group_control input[type=radio]",
  classLevelLabel:"#ClassificationLevel_radio_group_control .mr-2",
  classIL4RadioBtn: "#Radio_IL4Radio",
  classIL2RadioBtn: "#Radio_IL2Radio",
  classIL5RadioBtn: "#Radio_IL5Radio",
  classIL6RadioBtn: "#Radio_IL6Radio",
  classLevelTooltipBtn: "#TooltipButton_ClassificationLevel",
  classLevelTootipText: "#TooltipText_ClassificationLevel", 
  decriptionLabel: "#DescriptionOfNeed_text_field_label",
  performanceRadioGroup:"#PerformanceTier_radio_group_control input[type=radio]",
  performanceTierLabel:"#PerformanceTier_radio_group_control .mr-2",
  performanceTierTooltipBtn: "#TooltipButton_PerformanceTier",
  performanceTierTootipText: "#TooltipText_PerformanceTier",
  neededDurationActiveRadioBtn: "#NeededForEntireDuration_radio_group_control .v-item--active",
  baseCheckbox: "#Checkbox_BASE",
  formSectionTwoHeader: "#FormSection2Heading",
  operSysLicenLabel: "#OperatingSystemAndLicensing_text_field_label",
  operSysLicenTooltipBtn: "#TooltipButton_OperatingSystemAndLicensing",
  operSysLicenTootipText: "#TooltipText_OperatingSystemAndLicensing",
  operSysLicenTxtBox: "#OperatingSystemAndLicensing_text_field",
  operSysLicenError: "#OperatingSystemAndLicensing_text_field_control .field-error",
  noOfvCPULabel: "#NumberOfVCPUs_text_field_label",
  noOfvCPUTxtBox: "#NumberOfVCPUs_text_field",
  noOfvCPUTooltipBtn: "#TooltipButton_NumberOfVCPUs",
  noOfvCPUTooltipText: "#TooltipText_NumberOfVCPUs",
  noOfvCPUError: "#NumberOfVCPUs_text_field_control .field-error",
  memoryLabel: "#Memory_text_field_label",
  memoryTextBox: "#Memory_text_field",
  memoryTooltipBtn: "#TooltipButton_Memory",
  memoryTooltipTxt: "#TooltipText_Memory",
  memoryError: "#Memory_text_field_control .field-error",
  storageTypeLabel: "#StorageType_dropdown_field_label",
  storageTypeDropdown: "#StorageType_dropdown",
  storageTypeDropdownList:"#StorageType_dropdown_field_control [role=listbox]",
  storageTypeError: "#StorageType_dropdown_field_control .field-error",
  storageTypeGP: "#StorageType_DropdownListItem_GeneralPurposeSSD",
  storageTypePIOPS: "#StorageType_DropdownListItem_ProvisionedIOPSSSD",
  storageTypeNearline: "#StorageType_DropdownListItem_Nearline",
  storageTypeOffline: "#StorageType_DropdownListItem_Offline",
  storageTypeOther: "#StorageType_DropdownListItem_Other",
  storageAmountLabel: "#StorageAmount_text_field_label",
  storageAmountTextBox:"#StorageAmount_text_field",
  storageAmountTooltipBtn: "#TooltipButton_StorageAmount",
  storageAmountTooltipText: "#TooltipText_StorageAmount",
  storageAmountError: "#StorageAmount_text_field_control .field-error",
  noInstancesNeededLabel: "#NumberOfInstances_text_field_label",
  noInstancesNeededTooltipBtn: "#TooltipButton_NumberOfInstances",
  noInstancesNeededTooltipText: "#TooltipText_NumberOfInstances",
  entireDurationActiveBtn:"#EntireDuration_1_radio_group_control .v-item--active",
  premiumRadioBtn: "#Radio_PerformancePremium",
  standardRadioBtn: "#Radio_PerformanceStandard",
  basicRadioBtn: "#Radio_PerformanceBasic",
  otherRadioBtn: "#Radio_PerformanceOther", 
  otherPerTextField:"#OtherPerformance_text_field",
  updateCLLink: "#UpdateClassificationFromIntro",
    
  //Compute Requirements
  tableWrapper: ".v-data-table__wrapper",
  instanceOneEditBtn: "#EditButton_1",
  instanceOneDeleteBtn: "#DeleteButton_1",
  addAnotherInstance: "#AddInstance",
  instanceTwoEditBtn: "#EditButton_2",
  instanceTwoDeleteBtn: "#DeleteButton_2",
  dialogModal:".v-dialog",
  dialogTitle: "#DeleteInstanceModalTitle",
  deleteInstBtn: "#dialog_ok",
  
  //Let’s gather your requirements for general IaaS, PaaS and SaaS
  requirementTitleLabel: "#RequirementTitle_text_field_label",
  requirementTitleTooltipBtn: "#TooltipButton_RequirementTitle",
  requirementTitleTooltipText: "#TooltipText_RequirementTitle",
  requirementTitleTxtBox: "#RequirementTitle_text_field",

  //Your general IaaS, PaaS, and SaaS requirements  
  noReqTxt: ".w-100",
  optionOneCheckbox: "#Checkbox_OPTION1",
  
  //Next, we’ll gather your requirements for Migration Tools
  singleClassIntro: "#SingleClassificationIntro",
  classTextInIntro: "#SingleClassificationIntro p",
  classLevelsLabel: "#ClassificationGroupLabel",
  classCheckboxes: "#ClassificationCheckboxes input[type=checkbox]",
  contentAboutClass: "#Button_AboutClassificationLevels",
  contentText: "#Content_AboutClassificationLevels",
  updateLink: "#UpdateClassification",
  offeringDetailform: "#OfferingDetailsForms",
  anticipatedTextError1: "#AnticipatedNeedUsage_1_text_field_control .field-error",
  durationYesRadioBtn: "#Radio_Yes",
  durationNoRadioBtn: "#Radio_No",
  classReqAlertMess: "#ClassificationRequirementsAlert",
  periodCheckboxLabel1: "#PeriodsLabel_1",
  periodCheckboxRow1: "#PeriodsCheckboxes_1 ._checkbox",
  periodCheckbox1: "#PeriodsCheckboxes_1",
  baseCheckbox1Disabled: "#Checkbox_BaseDisabled",
  requirmentHeading1: "h2#RequirementHeading_1",
  anticipatedTextlabel1: "#AnticipatedNeedUsage_1_text_field_label",
  anticipatedTextBox1: "#AnticipatedNeedUsage_1_text_area",
  entireDurationRadioLabel1: "#EntireDuration_1_radio_group_control legend",
  duration1ActiveRadioBtn: "#EntireDuration_1_radio_group_control .v-item--active",
  duration1Error: "#EntireDuration_1_radio_group_control .field-error",
  checkBoxBase: "#Checkbox_BASE",
  alertPeriod1Text: "#PeriodIntro_1",
  baseCheck1Error: "#PeriodsCheckboxes_1 .field-error",
  contractDtailsLink: "#ContractDetailsLink_1",
  
  //Multiple classifications levels  
  requirmentHeading2: "h2#RequirementHeading_2",
  anticipatedTextlabel2: "#AnticipatedNeedUsage_2_text_field_label",
  anticipatedTextBox2: "#AnticipatedNeedUsage_2_text_area",
  entireDurationRadioLabel2: "#EntireDuration_2_radio_group_control legend",
  duration2NoRadioBtn: "#EntireDuration_2_radio_group_control #Radio_No",
  duration2ActiveRadioBtn: "#EntireDuration_2_radio_group_control .v-item--active",
  periodCheckboxLabel2: "#PeriodsLabel_2",
  periodCheckboxRow2: "#PeriodsCheckboxes_2 ._checkbox",
  periodCheckbox2: "#PeriodsCheckboxes_2",
  periodCheckBoxBase2: "#PeriodsCheckboxes_2 #Checkbox_BASE",
  
  //Update classification model
  updateModal: ".v-dialog",
  modaltitle: "#ClassificationLevelCheckboxesModalTitle",
  modalMessage: "#ClassificationLevelCheckboxesModalMessage > :nth-child(1)",
  modalCheckboxes: "#ClassificationLevelCheckboxesModal input[type=checkbox]:checked",
  level2: "#Checkbox_IL2Modal",
  level4: "#Checkbox_IL4Modal",
  level5: "#Checkbox_IL5Modal",
  level6: "#Checkbox_IL6Modal",
  modalCheckboxesError: "#ClassificationLevelCheckboxesModal .field-error",
  changeLevelBtn: "#dialog_ok",
  cancelBtn: "#dialog_cancel",
  toastText:".v-snack__content",
  
  //Summary
  selectedGroups: "#SelectedGroups",
  categoryNameHeader: "#SelectedGroups h3",
  serviceOfferingLabels: "#SelectedGroups p.mb-0._selectedOfferings",
  serviceOfferingSpans: "#SelectedGroups ._selectedOffering",
  missingInfo: "#SelectedGroups ._missing-info",
  reviewbtn: "#SelectedGroups button",
  otherCategories: "#OtherAvlGroups h2",
  showMoreLink: "#ShowMoreLink",
  otherCardHeaders:"#OtherAvlGroups .h3",
  contractDetailsLink: "#Step4Link",
  cardTitle: "#OtherAvlGroups .h3",
  computeHeading: "#Compute_Heading",
  computeTooltipBtn: "#TooltipButton_Compute",
  computeTooltipText: "#TooltipText_Compute",
  computeLink: "#Compute_Link",
  selectedGroupsBtn: "#SelectedGroups button",
  devBtn: "#DeveloperTools_Wrapper button",
  devHeading: "#DeveloperTools_Heading",
  devTooltipBtn: "#TooltipButton_DeveloperTools",
  devTooltipText: "#TooltipText_DeveloperTools",
  devLink: "#DeveloperTools_Link",
  appHeading: "#Applications_Heading",
  appTooltipBtn: "#TooltipButton_Applications",
  appTooltipText: "#TooltipText_Applications",
  appLink: "#Applications_Link",
  mlHeading: "#MachineLearning_Heading",
  mlTooltipBtn: "#TooltipButton_MachineLearning",
  mlTooltipText: "#TooltipText_MachineLearning",
  mlLink: "#MachineLearning_Link",
  netHeading: "#Networking_Heading",
  netTooltipBtn: "#TooltipButton_Networking",
  netTooltipText: "#TooltipText_Networking",
  netLink: "#Networking_Link",
  secHeading: "#Security_Heading",
  secTooltipBtn: "#TooltipButton_Security",
  secTooltipText: "#TooltipText_Security",
  secLink: "#Security_Link",
  dbHeading: "#Database_Heading",
  dbTooltipBtn: "#TooltipButton_Database",
  dbTooltipText: "#TooltipText_Database",
  dbLink: "#Database_Link",
  edHeading: "#EdgeComputing_Heading",
  edTooltipBtn: "#TooltipButton_EdgeComputing",
  edTooltipText: "#TooltipText_EdgeComputing",
  edLink: "#EdgeComputing_Link",
  iotHeading: "#Iot_Heading",
  iotTooltipBtn: "#TooltipButton_Iot",
  iotTooltipText: "#TooltipText_Iot",
  iotLink: "#Iot_Link",
  genHeading: "#GeneralXaas_Heading",
  genTooltipBtn: "#TooltipButton_GeneralXaas",
  genTooltipText: "#TooltipText_GeneralXaas",
  genLink: "#GeneralXaas_Link",
  adHeading: "#Advisory_Heading",
  adTooltipBtn: "#TooltipButton_Advisory",
  adTooltipText: "#TooltipText_Advisory",
  adLink: "#Advisory_Link",
  trainHeading: "#Training_Heading",
  trainTooltipBtn: "#TooltipButton_Training",
  trainTooltipText: "#TooltipText_Training",
  trainLink: "#Training_Link",

}  
