module.exports = {
  introPText: "p.mb-10",
  learnMoreLink: "p.mb-10 a",
  xaasLabelText: "#XaaSLabel",
  xaasCheckboxes:"#XaaSCheckboxes",
  cloudSupportCheckboxes: "#CloudSupportCheckboxes",
  cloudSupportLabelText: "#CloudSupportLabel",
  computeCheckBox: "#Checkbox_COMPUTE",
  devtoolsCheckBox: "#Checkbox_DEVELOPERTOOLS",
  appCheckBox: "#Checkbox_APPLICATIONS",
  machLearnCheckBox: "#Checkbox_MACHINELEARNING",
  networkCheckBox: "#Checkbox_NETWORKING",
  securityCheckBox: "#Checkbox_SECURITY",
  storageCheckBox: "#Checkbox_DATABASE",
  teCheckBox: "#Checkbox_EDGECOMPUTING",
  iotCheckBox: "#Checkbox_IOT",
  generalCheckBox: "#Checkbox_GENERALXAAS",
  xaasNoneCheckBox: "#Checkbox_XaaSNoneApply",
  advisoryCheckBox: "#Checkbox_ADVISORY",
  trainingCheckBox:"#Checkbox_TRAINING",
  xassCheckbBoxError:"#XaaSCheckboxes .field-error",
  cloudSupportCheckboxError:"#CloudSupportCheckboxes .field-error",
  
}