module.exports = {
  headerPortfolioTitle:"#NameHeader",
  headerPortofilioTextfield:"#HeaderTextField",
  tabsGroup: ".v-slide-group__wrapper",
  moreMenubtn: "#MoreMenuButton",
  moreMenuList: "#MoreMenu .v-menu__content .v-list",
  inviteMemMenu: "#InviteMembers_MenuItem",
  renamePortMenu: "#RenamePortfolio_MenuItem",
  leavePortMenu: "#LeavePortfolio_MenuItem",
  archivePortMenu: "#ArchivePortfolio_MenuItem",
  loginCSPMenu: "#LoginToCSPConsole_MenuItem",
  
  //infopanel
  infoBtn: "#Info_Button",
  slideoutPanel:"#SlideoutPanel",
  panelWrap: "#PanelWrap",
  aboutPortSection: "#AboutPortfolioSection",
  aboutPortHeader: "#AboutSectionHeader",
  descriptionTextArea:"#DrawerTextArea",
  statusLabel: "#StatusLabel",
  statusChip: "#StatusChip",
  cspLabel: "#CSPLabel",
  cspName: "#CSP",
  serviceAgencyLabel: "#ServiceAgencyLabel",
  serviceAgencyName: "#ServiceAgency",
  createdbyLabel: "#CreatedByLabel",
  createdbyName: "#CreatedBy",
  createdbyLink: "#CreatedBy._text-link",
  portMemTitle: "#PortfolioTitle",
  portMemCount: "#PortfolioMembersSection .color-base",
  addPortMemIcon: "#AddPortfolioMember",
  addMemModal: "#AddMembersModal",
  addMemTitle: "#AddMembersModal #modalDialogTitle",
  addMemBtn:"#AddMemberModal #dialog_ok",
  memName0: "#MemberName0",
  memNameLink: "#MemberName.pt-1",
  memName1:"#MemberName1",
  role0Dropdown: "#Role0_dropdown",
  role0Manager: "#Role0_DropdownListItem_Manager",
  role0Viewer: "#Role0_DropdownListItem_Viewer",
  activeRole0: "#Role0_dropdown_field_control .v-select__selection",
  removememModal: "#RemoveMemberModal #dialog_ok",
  removeModalTitle: "#RemoveMemberModal #modalDialogTitle",
  removeMemBtn:"#RemoveMemberModal #modalDialogTitle",
  role0Remove: "#Role0_DropdownListItem_Removefromportfolio",
  role0AboutRoles: "Role0_DropdownListItem_AboutRoles",
  lastManager: "#LastManager",
  activeRole1: "#Role1_dropdown_field_control .v-select__selection",
  role1Dropdown: "#Role1_dropdown",
  role1Manager: "#Role1_DropdownListItem_Manager",
  role1Viewer: "#Role1_DropdownListItem_Viewer",
  role1Remove: "#Role1_DropdownListItem_Removefromportfolio",
  role1AboutRoles: "#Role1_DropdownListItem_AboutRoles",
  fundingTrackerTab: "#FundingTracker_Tab",  
  taskOrderTab: "#TaskOrders_Tab",
  cspPortalAccessTab: "#CSPPortalAccess_Tab", 
  
  //fundingtrackerview
  portfoliodetailsCard: "#PortfolioDetailsCard",
  portfoliodetailsTitle: "#PortfolioDetailsCard h3",
  availableFunds: "#AvailableFunds",
  totalPortFundsTitle:"#PortfolioDetailsCard .pt-1.mb-0",
  totalPortfolioFunds: "#TotalPortfolioFunds",
  popDates: "#PoPDates",
  fundingStatusCard: "#FundingStatusArcChart",
  fundingstatusHeader: "#FundingStatusCard h3",
  financialAlert: "#FinancialDetailsAlert .mb-0",
  
  //modal dialog view
  emailLabel: "#PillboxLabel",
  emailInputbox: "#PillboxWrapper",
  modalRoleDropdownIcon:"#Role_dropdown_field_control ._dropdown-icon",
  roleDropdownList:"#Role_dropdown_field_control .v-menu__content .v-list",
  roleDropdownManager:"#Role_DropdownListItem_Manager",
  roleDropdownViewer:"#Role_DropdownListItem_Viewer",
  emailinputBoxError:"form.v-form .field-error.ml-2",  
  
}
