module.exports = {
  //Portfolio summary card view
  summaryHeader: "#NameHeader",
  portHeadersTab:"._header-tab .v-tabs-bar__content",
  allPortTab: "#Allportfolios_Tab",
  processTab: "#Processing_Tab",
  activeTab: "#Active_Tab",
  searchInput: "#SearchPortfolios_SearchInput",
  searchBtn: "#SearchPortfolios_SearchButton",
  searchWrapper: "#SearchWrapper",
  portSortDowndrop: "#PortfolioSort_dropdown",
  portSortListItems:"#PortfolioSort_dropdown_field_control .v-menu__content .v-list",
  portNameSortAZ: "#PortfolioSort_DropdownListItem_PortfolionameAZ",
  recentlymod: "#PortfolioSort_DropdownListItem_Recentlymodified",
  filterBtn: "#FilterButton",
  filterSlideout: "._slideout-panel",
  panelCloser: "#PanelCloser",
  panelTitle: "#PanelTitle",
  radioAll: "#Radio_All",
  managedRadio:"#Radio_Managed",
  portfolioRoleRadioGroup: "#PortfolioRole_radio_group_control input[type=radio]",
  portfolioRadioActive:"#PortfolioRole_radio_group_control .v-item--active",
  fundingStatusLabel: "#FundingStatusLabel",
  fundingStatusCheckbox: "#FundingStatus input[type=checkbox]",
  fundingstatusActive: "#FundingStatus input[type=checkbox]:checked",
  trackCheckbox: "#Checkbox_OnTrack",
  expiringSoonCheckbox: "#Checkbox_ExpiringSoon",
  fundingRiskCheckbox: "#Checkbox_AtRisk",
  delinquent:"#Checkbox_Delinquent",
  cspOptionsLabel: "#CSPOptionsLabel",
  cspOptions: "#CSPOptions input[type=checkbox]",
  cspActive: "#CSPOptions input[type=checkbox]:checked",
  awsCheckbox: "#Checkbox_Amazon",
  azureCheckBox:"#Checkbox_Azure",
  resetFiltersLink: "#ResetFilters",
  applyFiltersLink:"#ApplyFilters",
  portfolioCards: "#PortfolioCards",
  portfolioName:"#PortfolioCards ._portfolio-name",
  noSearchResultHeader: "#NoResultsFound #NoResultsHeader",
  searchString: "#NoResultsFound #SearchString",
  withFilterString:"#WithFilters",
  clearSearchBtn: "#ClearSearchButton",
  awsFilterChip: "#FilterChip_Amazon",
  azureFilterChip: "#FilterChip_Azure",
  gcpFilterChip: "#FilterChip_GoogleCloud",
  oracleFilterChip: "#FilterChip_Oracle",
  fundATRiskChip: "#FilterChip_AtRisk",
  expiringSoonFilterChip: "#FilterChip_ExpiringSoon",
  onTrackFilterChip: "#FilterChip_On track",
  deinquentFilterChip: "#FilterChip_Delinquent",  
  portfolioStatusChip: "#PortfolioCards .v-chip--label",  
  summaryCardWrapper: "._summary-card-wrapper",
  cspOption:"._csp-icon-wrap",
  card0MenuListItem:"#PortfolioCardMenu0_0  .v-list",
  portfolioCardOne: "#PortfolioCardMenu0Button_0",
  ftOne: "#Viewfundingtracker_MenuItem0",
  toOne: "#Viewtaskorders_MenuItem0",
  emailPMOne: "#Emailportfoliomanagers_MenuItem0",
  leavePortOne: "#Leavethisportfolio_MenuItem0",
  headerPortfolioTitle:"#NameHeader",
  headerPortfolioTextfield:"#HeaderTextField",
  tabsGroup: ".v-slide-group__wrapper",
  moreMenubtn: "#MoreMenuButton",
  moreMenuList: "#MoreMenu .v-menu__content .v-list",
  inviteMemMenu: "#InviteMembers_MenuItem",
  renamePortMenu: "#RenamePortfolio_MenuItem",
  leavePortMenu: "#LeavePortfolio_MenuItem",
  archivePortMenu: "#ArchivePortfolio_MenuItem",
  loginCSPMenu: "#LoginToCSPConsole_MenuItem",
  
  //infopanel
  infoBtn: "#Info_Button",
  slideoutPanel:"#SlideoutPanel",
  panelWrap: "#PanelWrap",
  aboutPortSection: "#AboutPortfolioSection",
  aboutPortHeader: "#AboutSectionHeader",
  descriptionTextArea:"#DrawerTextArea",
  statusLabel: "#StatusLabel",
  statusChip: "#StatusChip",
  cspLabel: "#CSPLabel",
  cspName: "#CSP",
  agencyLabel: "#AgencyLabel",
  agencyName: "#Agency",
  createdbyLabel: "#CreatedByLabel",
  createdbyName: "#CreatedBy",
  createdbyLink: "#CreatedBy._text-link",
  portMemTitle: "#PortfolioTitle",
  portMemCount: "#PortfolioMembersSection .color-base",
  addPortMemIcon: "#AddPortfolioMember",
  addMemModal: "#AddMembersModal",
  addMemTitle: "#AddMembersModalTitle",
  addMemBtn:"#AddMemberModal #dialog_ok",
  memName0: "#MemberName0",
  memNameLink: "#MemberName.pt-1",
  memName1:"#MemberName1",
  role0Dropdown: "#Role0_dropdown",
  role0Manager: "#Role0_DropdownListItem_Manager",
  role0Viewer: "#Role0_DropdownListItem_Viewer",
  activeRole0: "#Role0_dropdown_field_control .v-select__selection",
  removememModal: "#RemoveMemberModal #dialog_ok",
  removeModalTitle: "#RemoveMemberModalTitle",
  role0Remove: "#Role0_DropdownListItem_Removefromportfolio",
  role0AboutRoles: "Role0_DropdownListItem_AboutRoles",
  lastManager: "#LastManager",
  activeRole1: "#Role1_dropdown_field_control .v-select__selection",
  role1Dropdown: "#Role1_dropdown",
  role1Manager: "#Role1_DropdownListItem_Manager",
  role1Viewer: "#Role1_DropdownListItem_Viewer",
  role1Remove: "#Role1_DropdownListItem_Removefromportfolio",
  role1AboutRoles: "#Role1_DropdownListItem_AboutRoles",
  fundingTrackerTab: "#FundingTracker_Tab",  
  taskOrderTab: "#TaskOrders_Tab",
  cspPortalAccessTab: "#CSPPortalAccess_Tab", 
  
  //fundingtrackerview
  portfoliodetailsCard: "#PortfolioDetailsCard",
  portfoliodetailsTitle: "#PortfolioDetailsCard h3",
  availableFunds: "#AvailableFunds",
  totalPortFundsTitle:"#PortfolioDetailsCard .pt-1.mb-0",
  totalPortfolioFunds: "#TotalPortfolioFunds",
  popDates: "#PoPDates",
  fundingStatusCard: "#FundingStatusArcChart",
  fundingstatusHeader: "#FundingStatusHeader",
  financialAlert: "#FinancialDetailsAlert .mb-0",

  //TaskOrder view
  allTO:"h2",
  toLinkOne: "#TaskOrderLink0",
  popOne: "#PoP0",
  obligatedFundOne: "#ObligatedFunds0",
  totalValueOne: "#TotalValue0",
  totalLFundsSpent: "#FundsSpent0",
  viewTODetailsLink0: "#Viewtaskorderdetails_MenuItem0",
  reqTomodifyTOLink0: "#Requesttomodifytaskorder_MenuItem0",
  taskOrderDetails:"._task-order-details",
  taskorderlink: "#LinkToTaskOrders",
  taskorderNumber: "#TaskOrderNumber",
  clinDataTable: "#CLINDataTable",
  clinHeaderRow: "#CLINDataTable .v-data-table-header",
  inactiveToggle: "#InactiveToggle",
  totalObligatedFundsCard: "#Card_TotalObligatedFunds .h1",
  tooltipBtnOFC: "#TooltipButton_ObligatedFundsToolTip",
  tooltipTextOFC: "#TooltipText_ObligatedFundsToolTip",
  totalTOValueCard: "#Card_TotalTaskOrderValue .h1",
  tooltipBtnTOV: "#TooltipButton_TotalValueToolTip",
  tooltipTextTOV: "#TooltipText_TotalValueToolTip",
  totalLifeCycleAmount: "#Card_TotalLifecycleAmount .h1",
  tooltipBtnLCA: "#TooltipButton_LifecycleToolTip",
  tooltipTextLCA: "#TooltipText_LifecycleToolTip",
  totalFundsSpent: "#Card_TotalFundsSpent .h1",
  tooltipBtnTFS: "#TooltipButton_TotalFundsToolTip",
  tooltipTextTFS: "#TooltipText_TotalFundsToolTip",
  expirationLink: "._expiration",
  taskOrderHistoryHeader:".v-expansion-panel-header h2",
  taskOrderHistory: "#TaskOrderHistoryNumber",
  grandTotalObValue: "._grand-total-obligated-funds span",
  grandHiddenTotalObValue:"td:nth-child(3)._grand-total-clin-value span",
  grandTotalCLINSValue: "._grand-total-clin-value span",
  grandhiddenTotalCLINSValue: "td:nth-child(4)._grand-total-obligated-funds span",
  grandTotalFundsSpentValue: "._grand-total-funds-spent",
  optionPendingCLINsValue:"._total-clin-value._OPTION_PENDING",
  
  //CSP Portal Access
  cspTitle: "#CSPTitle.h3",
  cspDescription: "#CSPDescription",
  learnMorkLink: "#LearnMoreLink",
  cspAdminLogLabel: "#TableHeader",
  addCSPAdminBtn: "#AddCSPAdmin",
  addCSPModal: "#AddCSPMember",
  modalMessage: "#UpdateClassificationsModalMessage p.body",
  modallearnlink: "#AddCSPMember #LearnMoreLink",
  modalSlideOut: "#AddCSPMember #ModalSlideoutTitle",
  modalSlideoutCloser:"#AddCSPMember #ModalSlideoutCloser",
  addCSPModalTitle: "#AddCSPMemberTitle",
  modalAddAdminBtn: "#AddCSPMember #dialog_ok",
  modalCancelBtn:"#AddCSPMember #dialog_cancel",
  adminEmailAddressLabel: "#AdministratorEmail_text_field_label",
  adminEmailAddressTextBox: "#AdministratorEmail_text_field",
  adminEmailAddressHelpText: "#AdministratorEmail_text_field_control .help-text",
  adminEmailAddressError: "#AdministratorEmail_text_field_control .field-error",
  adminDoDIDLabel: "#AdministratorDODID_text_field_label",
  adminDoDIDTextbox: "#AdministratorDODID_text_field",
  adminDoDIDError: "#AdministratorDODID_text_field_control .field-error",
  adminDoDToolTipBtn: "#TooltipButton_AdministratorDODID",
  adminDoDToolTipText: "#TooltipText_AdministratorDODID",
  tablePagination: "ul.v-pagination",
  tablepageText: "._table-pagination .mr-11",
  firstRow: "table > tbody > tr:nth-child(1) > td",
  headerRow:"table> thead th span",
  
  //modal dialog view
  emailLabel: "#PillboxLabel",
  emailInputbox: "#PillboxWrapper",
  modalRoleDropdownIcon:"#Role_dropdown_field_control ._dropdown-icon",
  roleDropdownList:"#Role_dropdown_field_control .v-menu__content .v-list",
  roleDropdownManager:"#Role_DropdownListItem_Manager",
  roleDropdownViewer:"#Role_DropdownListItem_Viewer",
  emailinputBoxError:"form.v-form .field-error.ml-2",  
  
}
