module.exports = {
  //Portfolio summary card view
  summaryHeader: "#NameHeader",
  allPortTab: "#Allportfolios_Tab",
  processTab: "#Processing_Tab",
  activeTab: "#Active_Tab",
  searchInput: "#SearchPortfolios_SearchInput",
  searchBtn: "#SearchPortfolios_SearchButton",
  portfolioCards:"#PortfolioCards",
  card0MenuListItem:"#PortfolioCardMenu0_0  .v-list",
  portfolioCardOne: "#PortfolioCardMenu0Button_0",
  ftOne: "#Viewfundingtracker_MenuItem0",
  toOne: "#Viewtaskorders_MenuItem0",
  emailPMOne: "#Emailportfoliomanagers_MenuItem0",
  leavePortOne: "#Leavethisportfolio_MenuItem0",
  headerPortfolioTitle:"#NameHeader",
  headerPortfolioTextfield:"#HeaderTextField",
  tabsGroup: ".v-slide-group__wrapper",
  moreMenubtn: "#MoreMenuButton",
  moreMenuList: "#MoreMenu .v-menu__content .v-list",
  inviteMemMenu: "#InviteMembers_MenuItem",
  renamePortMenu: "#RenamePortfolio_MenuItem",
  leavePortMenu: "#LeavePortfolio_MenuItem",
  archivePortMenu: "#ArchivePortfolio_MenuItem",
  loginCSPMenu: "#LoginToCSPConsole_MenuItem",
  
  //infopanel
  infoBtn: "#Info_Button",
  slideoutPanel:"#SlideoutPanel",
  panelWrap: "#PanelWrap",
  aboutPortSection: "#AboutPortfolioSection",
  aboutPortHeader: "#AboutSectionHeader",
  descriptionTextArea:"#DrawerTextArea",
  statusLabel: "#StatusLabel",
  statusChip: "#StatusChip",
  cspLabel: "#CSPLabel",
  cspName: "#CSP",
  agencyLabel: "#AgencyLabel",
  agencyName: "#Agency",
  createdbyLabel: "#CreatedByLabel",
  createdbyName: "#CreatedBy",
  createdbyLink: "#CreatedBy._text-link",
  portMemTitle: "#PortfolioTitle",
  portMemCount: "#PortfolioMembersSection .color-base",
  addPortMemIcon: "#AddPortfolioMember",
  addMemModal: "#AddMembersModal",
  addMemTitle: "#AddMembersModal #modalDialogTitle",
  addMemBtn:"#AddMemberModal #dialog_ok",
  memName0: "#MemberName0",
  memNameLink: "#MemberName.pt-1",
  memName1:"#MemberName1",
  role0Dropdown: "#Role0_dropdown",
  role0Manager: "#Role0_DropdownListItem_Manager",
  role0Viewer: "#Role0_DropdownListItem_Viewer",
  activeRole0: "#Role0_dropdown_field_control .v-select__selection",
  removememModal: "#RemoveMemberModal #dialog_ok",
  removeModalTitle: "#RemoveMemberModal #modalDialogTitle",
  removeMemBtn:"#RemoveMemberModal #modalDialogTitle",
  role0Remove: "#Role0_DropdownListItem_Removefromportfolio",
  role0AboutRoles: "Role0_DropdownListItem_AboutRoles",
  lastManager: "#LastManager",
  activeRole1: "#Role1_dropdown_field_control .v-select__selection",
  role1Dropdown: "#Role1_dropdown",
  role1Manager: "#Role1_DropdownListItem_Manager",
  role1Viewer: "#Role1_DropdownListItem_Viewer",
  role1Remove: "#Role1_DropdownListItem_Removefromportfolio",
  role1AboutRoles: "#Role1_DropdownListItem_AboutRoles",
  fundingTrackerTab: "#FundingTracker_Tab",  
  taskOrderTab: "#TaskOrders_Tab",
  cspPortalAccessTab: "#CSPPortalAccess_Tab", 
  
  //fundingtrackerview
  portfoliodetailsCard: "#PortfolioDetailsCard",
  portfoliodetailsTitle: "#PortfolioDetailsCard h3",
  availableFunds: "#AvailableFunds",
  totalPortFundsTitle:"#PortfolioDetailsCard .pt-1.mb-0",
  totalPortfolioFunds: "#TotalPortfolioFunds",
  popDates: "#PoPDates",
  fundingStatusCard: "#FundingStatusArcChart",
  fundingstatusHeader: "#FundingStatusHeader",
  financialAlert: "#FinancialDetailsAlert .mb-0",

  //CSP Portal Access
  cspTitle: "#CSPTitle.h3",
  cspDescription: "#CSPDescription",
  learnMorkLink: "#LearnMoreLink",
  cspAdminLogLabel: "#TableHeader",
  addCSPAdminBtn: "#AddCSPAdmin",
  addCSPModal: "#AddCSPMember",
  modalMessage: "#modalDialogMessage p.body",
  modallearnlink: "#AddCSPMember #LearnMoreLink",
  modalSlideOut: "#AddCSPMember #ModalSlideoutTitle",
  modalSlideoutCloser:"#AddCSPMember #ModalSlideoutCloser",
  addCSPModalTitle: "#AddCSPMember #modalDialogTitle",
  modalAddAdminBtn: "#AddCSPMember #dialog_ok",
  modalCancelBtn:"#AddCSPMember #dialog_cancel",
  adminEmailAddressLabel: "#AdministratorEmail_text_field_label",
  adminEmailAddressTextBox: "#AdministratorEmail_text_field",
  adminEmailAddressHelpText: "#AdministratorEmail_text_field_control .help-text",
  adminEmailAddressError: "#AdministratorEmail_text_field_control .field-error",
  adminDoDIDLabel: "#AdministratorDODID_text_field_label",
  adminDoDIDTextbox: "#AdministratorDODID_text_field",
  adminDoDIDError: "#AdministratorDODID_text_field_control .field-error",
  adminDoDToolTipBtn: "#TooltipButton_AdministratorDODID",
  adminDoDToolTipText: "#TooltipText_AdministratorDODID",
  tablePagination: "ul.v-pagination",
  tablepageText: "._table-pagination .mr-11",
  firstRow: "table > tbody > tr:nth-child(1) > td",
  headerRow:"table> thead th span",
  
  //modal dialog view
  emailLabel: "#PillboxLabel",
  emailInputbox: "#PillboxWrapper",
  modalRoleDropdownIcon:"#Role_dropdown_field_control ._dropdown-icon",
  roleDropdownList:"#Role_dropdown_field_control .v-menu__content .v-list",
  roleDropdownManager:"#Role_DropdownListItem_Manager",
  roleDropdownViewer:"#Role_DropdownListItem_Viewer",
  emailinputBoxError:"form.v-form .field-error.ml-2",  
  
}
