module.exports = {
  //PII
  blueInfoMessageText:"._atat-alert",
  piiRadioOptionText: "#PIIOptions_radio_group_control legend",
  piiRadioOtionActive: "#PIIOptions_radio_group_control .v-item--active",
  piiRadioError:"#PIIOptions_radio_group_control .field-error",
  yesPIIRadioOption: "#Radio_YesPII",
  noPIIRadioOption: "#Radio_NoPII",
  piiLink: "#Button_PIIFAQ",
  piiFAQText: "#Content_PIIFAQ p.mb-4",
  patLink: "#PrivacyActLink1",
  paLink: "#PrivacyActLink2",
  moreInfoLink: "#PrivacyActLink3",
  //PII-Tell Us More about your system of records
  systemLabel: "#SystemName_text_field_label",
  systemNameTextBox: "#SystemName_text_field",
  systemNameError:"#SystemName_text_field_control .field-error",
  operationPerformedLabel: "#OperationToBePerformed_text_field_label",
  operationPerformedTextBox: "#OperationToBePerformed_text_area",
  operationPerformedError:"#OperationToBePerformed_text_field_control .field-error",
  //BAA
  baaLabelText: "._atat-alert h2",
  phiTextMessage: "._atat-alert._callout p",
  learnMoreBAALink: "#LearnMoreBAA",
  baaRadioOptionText: "#BAARadioOptions_radio_group_control legend",
  baaRadioOptionActive: "#BAAOptions_radio_group_control .v-item--active",
  yesBAARadioOption: "#Radio_YesBAA",
  noBAARadioOption: "#Radio_NoBAA",
  aboutBALink: "#Button_AboutBusinessAssociates",
  contentAboutBA: "#Content_AboutBusinessAssociates",
  baaRadioError:"#BAARadioOptions_radio_group_control .field-error",
  moreInfoBAALink: "a._text-link._external-link",
  infoAlert: "._atat-alert._info-alert p",
  //FOIA
  foiaYesOption: "#Radio_Yes",
  foiaNoOption: "#Radio_No",
  foiaRadioError:"#FOIAOptions_radio_group_control .field-error",
  foiaRadioOptionActive:"#FOIAOptions_radio_group_control .v-item--active",
  foiaLearnLink: "#FOIALearnMore",
  foiaLearnDrawer: ".v-navigation-drawer__content",
  learnMoreDrawerLabel: "#PanelTitle",
  learnMoreHeaderTxt: "._slideout-panel h2",
  learnMoreDrawerClose: "#PanelCloser",
  learnMoreFOIAUrl: "._text-link",
  foiaFAQLink: "#Button_FOIAFAQ",
  foiaFAQText: "#Content_FOIAFAQ",
  //Tell us about your FOIA cordinator
  fullNameLabel: "#FullName_text_field_label",
  fullNameTxtBox: "#FullName_text_field",
  fullNameError:"#FullName_text_field_control .field-error",
  fullNameHelpTxt: "#FullName_text_field_control .help-text",
  emailLabel: "#Email_text_field_label",
  emailTxtbox: "#Email_text_field",
  emailError:"#Email_text_field_control .field-error",
  emailHelpTxt: "#Email_text_field_control .help-text",
  //508 standards
  introText: "#IntroP",
  blueAlertLabel: "._atat-alert h2",
  scrollBar: "div._atat-alert.mb-10._callout._scrollable.py-0.pr-0",
  secton508Text: "#Section508RadioGroup_radio_group_control legend",
  sectionYesRadio: "#Radio_Yes",
  sectionNoRadio: "#Radio_No",
  about508Link: "#Button_AboutBusinessAssociates",
  sectionradioActive: "#Section508RadioGroup_radio_group_control .v-item--active",
  sectionradioError: "#Section508RadioGroup_radio_group_control .field-error",
  //Tell us more about your Section 508 Accessibility Requirements
  accessibilityLink: "#508AccessibilityExternalLink",
  accessibilityLabelTxt: "#OperationToBePerformed_text_field_label",
  accessibilityHelpTxt: "#OperationToBePerformed_text_field_control .help-text",
  operationTxtBox: "#OperationToBePerformed_text_area",
  operationTxtError:"#OperationToBePerformed_text_field_control .field-error",
}
