<template>
  <v-form ref="form" lazy-validation>
    <v-container fluid class="container-max-width">
      <v-row>
        <v-col class="col-12">
          <h1 class="page-header mb-3">
            Let’s gather your General Terms & Conditions (GT&C) information
          </h1>
          <div class="copy-max-width">
            <p class="mb-10">
              Your organization must have a GT&C agreement to transfer funds to
              {{ ditcoOrContractingOffice }}. To save time, we recommend
              completing this information within G-Invoicing. However, you may
              also upload a completed Fiscal Service (FS) Form 7600A, if needed.
              <a
                role="button"
                id="GInvoicingLearnMore"
                class="_text-link"
                tabindex="0"
                @click="openSlideoutPanel"
                @keydown.enter="openSlideoutPanel"
                @keydown.space="openSlideoutPanel"
              >
                Learn more about G-Invoicing
              </a>
            </p>
            <ATATRadioGroup
              class="max-width-640"
              id="GInvoicingOptions"
              legend="Did you use G-Invoicing for your GT&C?"
              :items="gInvoicingOptions"
              :value.sync="useGInvoicing"
              :rules="[$validators.required('Please select an option')]"
            />
            <ATATExpandableLink aria-id="Instructions" class="mt-4">
              <template v-slot:header>
                What if I don’t have a GT&C agreement yet?
              </template>
              <template v-slot:content>
                <p class="mt-4">
                  We recommend contacting your agency’s resource management
                  division or financial department to determine the best method
                  for initiating a Fiscal Service Form 7600A (i.e., GT&C), as
                  well as a funding request (e.g., a Fiscal Service Form 7600B,
                  an Order within G-Invoicing, or a Military Interdepartmental
                  Purchase Request).
                </p>
                <p>
                  If you are asked to provide documentation for your
                  requirements package to obtain these funding documents, you
                  can skip this section and proceed to the “Generate Package
                  Documents” section to download your completed documents. Prior
                  to submitting your package to {{ ditcoOrContractingOffice }},
                  you will need to return to this section to update your funding
                  details. This will allow you to re-generate a complete package
                  that includes your funding document numbers on any affected
                  documents.
                </p>
              </template>
            </ATATExpandableLink>
          </div>
          <div v-show="useGInvoicing === 'YES'">
            <hr class="mt-5" />
            <!-- eslint-disable max-len -->
            <ATATSearch
              id="GTCNumberSearch"
              placeHolder="Find your order in G-Invoicing"
              label="General Terms & Conditions (GT&C) Number"
              tooltipText="This is a 20-character value (including hyphens) generated by G-Invoicing."
              :width="'388px'"
              :hideHelpTextOnErrors="true"
              :validate-on-blur="true"
              :value.sync="gInvoiceNumber"
              helpText="Format: AYYMM-000-000-000000"
              searchType="G-Invoicing"
              gInvoicingSearchType="GtcNumber"
              :rules="[
                $validators.isMaskValid(
                  ['A[0-9]{4}\-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$'],
                  `Your GT&C Number should be 20 characters (including hyphens) and use the format: AYYMM-000-000-000000.`,
                  true
                ),
                $validators.required('Please provide a GT&C number.'),
              ]"
              :triggerSearch="triggerSearch"
              @onGInvoiceSearchComplete="onGInvoiceSearchComplete"
            />
            <!-- eslint-enable -->
          </div>
          <div v-show="useGInvoicing === 'NO'">
            <hr class="mt-5" />
            <div style="width: 460px">
              <ATATTextField
                id="GTCNumberText"
                label="General Terms & Conditions (GT&C) Number"
                tooltipText="This is a 20-character value (including hyphens) generated by G-Invoicing. Your GT&C Number is located in the top section of your <strong>FS Form 7600A.</strong>"
                :width="'388'"
                :hideHelpTextOnErrors="true"
                :validate-on-blur="true"
                :value.sync="gInvoiceNumber"
                helpText="Format: AYYMM-000-000-000000"
                :rules="[
                  $validators.isMaskValid(
                    ['A[0-9]{4}\-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$'],
                    `Your GT&C Number should be 20 characters (including hyphens) and use the format: AYYMM-000-000-000000.`,
                    true
                  ),
                  $validators.required('Please provide a GT&C number.'),
                ]"
              />
            </div>
            <hr class="mv-5" />
            <h2 class="h2 pb-5">Upload your FS Form 7600A</h2>
            <ATATFileUpload
              :validFileFormats="validFileFormats"
              :attachmentServiceName="attachmentServiceName"
              :maxFileSizeInBytes="maxFileSizeInBytes"
              id="FundingPlan"
              @delete="onRemoveAttachment"
              fileListTitle="Your files"
              :invalidFiles.sync="invalidFiles"
              :maxNumberOfFiles="1"
              :multiplesAllowed="false"
              :validFiles.sync="uploadedFiles"
              :requiredMessage="requiredMessage"
              :rules="getRulesArray()"
              :confirmRemoval="true"
              :confirmRemovalTitle="'Delete funding document?'"
              :confirmRemovalMessage="confirmRemoveFileMessage"
            />
          </div>
        </v-col>
      </v-row>
    </v-container>
  </v-form>
</template>
<script lang="ts">
import { invalidFile, uploadingFile } from "types/Global";
import { Component, Mixins } from "vue-facing-decorator";
import ATATRadioGroup from "@/components/ATATRadioGroup.vue";
import ATATSearch from "@/components/ATATSearch.vue";
import ATATExpandableLink from "@/components/ATATExpandableLink.vue";
import GInvoiceLearnMore from "@/steps/10-FinancialDetails/GInvoiceLearnMore.vue";
import SlideoutPanel from "@/store/slideoutPanel/index";
import AcquisitionPackage from "@/store/acquisitionPackage";
import { TABLENAME as FUNDING_REQUEST_FSFORM_TABLE } from "@/api/fundingRequestFSForm";
import Attachments from "@/store/attachments";

import {
  baseGInvoiceData,
  RadioButton,
  SlideoutPanelContent,
} from "../../../types/Global";
import FinancialDetails, {
  initialFundingRequestFSForm,
} from "@/store/financialDetails";

import SaveOnLeave from "@/mixins/saveOnLeave";
import { hasChanges } from "@/helpers";
import ATATTextField from "@/components/ATATTextField.vue";
import ATATFileUpload from "@/components/ATATFileUpload.vue";
import { AttachmentDTO, FundingRequestFSFormDTO } from "@/api/models";

@Component({
  components: {
    ATATRadioGroup,
    ATATSearch,
    ATATTextField,
    ATATFileUpload,
    GInvoiceLearnMore,
    ATATExpandableLink,
  },
})
export default class GTCInformation extends Mixins(SaveOnLeave) {
  // radio options
  public useGInvoicing: "YES" | "NO" | "" = "";
  private gInvoicingOptions: RadioButton[] = [
    {
      id: "Yes",
      label: "Yes. My GT&C Number is in G-Invoicing.",
      value: "YES",
    },
    {
      id: "No",
      label: "No. I would like to upload a completed FS Form 7600A.",
      value: "NO",
    },
  ];

  // gtc number text field
  public gInvoiceNumber = "";
  private triggerSearch = false;
  private gInvoiceSearchValid = false;

  // file upload
  private validFileFormats = ["pdf"];
  private attachmentServiceName = FUNDING_REQUEST_FSFORM_TABLE;
  private maxFileSizeInBytes = 1073741824;
  private invalidFiles: invalidFile[] = [];
  private uploadedFiles: uploadingFile[] = [];
  private loaded: FundingRequestFSFormDTO | null = null;

  private requiredMessage =
    "You must include an authorized 7600A for this acquisition. " +
    "Upload your missing document.";

  public openSlideoutPanel(e: Event): void {
    if (e?.currentTarget) {
      SlideoutPanel.openSlideoutPanel((e.currentTarget as HTMLElement).id);
    }
  }

  public get ditcoOrContractingOffice(): string {
    return AcquisitionPackage?.contractingShop === "DITCO"
      ? "DITCO"
      : "your Contracting Office";
  }

  public get currentData(): baseGInvoiceData {
    return {
      useGInvoicing: this.useGInvoicing,
      gInvoiceNumber: this.gInvoiceNumber,
    };
  }

  public savedData: baseGInvoiceData = {
    useGInvoicing: "",
    gInvoiceNumber: "",
  };

  private get confirmRemoveFileMessage() {
    return (
      (this.uploadedFiles?.[0]?.fileName
        ? `"${this.uploadedFiles[0].fileName}"`
        : "This file") +
      " will be permanently removed " +
      "from your acquisition package. This action cannot be undone."
    );
  }

  private onGInvoiceSearchComplete(validity: boolean) {
    this.gInvoiceSearchValid = validity;
  }

  // rules array dynamically created based on the invalid
  // files returned from the child component
  // `ATATFileUpload.vue`
  private getRulesArray(): ((v: string) => string | true | undefined)[] {
    if (this.useGInvoicing === "YES") return [];
    //eslint-disable-next-line prefer-const
    let rulesArr: ((v: string) => string | true | undefined)[] = [];

    rulesArr.push(this.$validators.required(this.requiredMessage));

    this.invalidFiles.forEach((iFile) => {
      rulesArr.push(
        this.$validators.isFileValid(
          iFile.file,
          this.validFileFormats,
          this.maxFileSizeInBytes,
          iFile.doesFileExist,
          iFile.SNOWError,
          iFile.statusCode
        )
      );
    });

    return rulesArr;
  }

  async onRemoveAttachment(file: uploadingFile): Promise<void> {
    try {
      if (file) {
        const key = this.attachmentServiceName;
        const attachmentId = file.attachmentId;
        const recordId = file.recordId;
        await Attachments.removeAttachment({
          key,
          attachmentId,
          recordId,
        });

        //get updated data
        await this.loadFundingRequestData();
      }
    } catch (error) {
      console.error(`error removing attachment with id ${file?.attachmentId}`);
    }
  }

  async loadFundingRequestData(): Promise<void> {
    this.loaded = await FinancialDetails.loadFundingRequestFSForm();
    this.gInvoiceNumber = this.loaded?.gt_c_number ?? "";

    // temporarily infering this useGInvoicing until accounts are properly migrated
    // if the new form a/b independant use_g_invoicing is already saved use that
    // else if the previous joined use_g_invoicing is saved, use that
    // else infer the use_g_invoicing by existence of form_attachment
    if (
      this.loaded?.fs_form_7600a_use_g_invoicing === "YES" ||
      this.loaded?.fs_form_7600a_use_g_invoicing === "NO"
    ) {
      this.useGInvoicing = this.loaded.fs_form_7600a_use_g_invoicing;
    } else if (
      this.loaded?.use_g_invoicing === "YES" ||
      this.loaded?.use_g_invoicing === "NO"
    ) {
      this.useGInvoicing = this.loaded?.use_g_invoicing;
    } else {
      this.useGInvoicing = this.loaded?.fs_form_7600a_attachment ? "NO" : "YES";
    }

    this.savedData = {
      useGInvoicing: this.useGInvoicing,
      gInvoiceNumber: this.gInvoiceNumber,
    };

    if (this.gInvoiceNumber && this.useGInvoicing) this.triggerSearch = true;
  }

  /**
   * Constructs an array of attachment table primary key sys ids based on the forms
   * uploaded. Uses the array to load the attachments.
   */
  async loadAttachments(): Promise<void> {
    const attachmentSysIds = [];
    if (
      this.loaded?.fs_form_7600a_attachment &&
      this.loaded?.fs_form_7600a_attachment.length > 0
    ) {
      attachmentSysIds.push(this.loaded?.fs_form_7600a_attachment);
    }
    const attachments = await Attachments.getAttachmentsBySysIds({
      serviceKey: FUNDING_REQUEST_FSFORM_TABLE,
      sysIds: attachmentSysIds,
    });
    const uploadedFiles = attachments.map((attachment: AttachmentDTO) => {
      const file = new File([], attachment.file_name, {
        lastModified: Date.parse(attachment.sys_created_on ?? ""),
      });
      const upload: uploadingFile = {
        attachmentId: attachment.sys_id ?? "",
        fileName: attachment.file_name,
        file: file,
        created: file.lastModified,
        progressStatus: 100,
        link: attachment.download_link ?? "",
        recordId: attachment.table_sys_id,
        isErrored: false,
        isUploaded: true,
      };
      return upload;
    });
    this.uploadedFiles = [...uploadedFiles];
  }

  async loadOnEnter(): Promise<void> {
    try {
      await this.loadFundingRequestData();
      await this.loadAttachments();
    } catch (error) {
      throw new Error("an error occurred loading funding plans data");
    }
  }

  public async mounted(): Promise<void> {
    const slideoutPanelContent: SlideoutPanelContent = {
      component: GInvoiceLearnMore,
      title: "Learn More",
    };
    await SlideoutPanel.setSlideoutPanelComponent(slideoutPanelContent);
    await this.loadOnEnter();
  }

  protected async saveOnLeave(): Promise<boolean> {
    if (
      this.gInvoiceSearchValid !== true && this.useGInvoicing === 'YES'
    ) return false;
    await AcquisitionPackage.setValidateNow(true);
    // file upload / saving
    try {
      if (this.hasChanged()) {
        this.loaded = await FinancialDetails.loadFundingRequestFSForm();
        /* eslint-disable camelcase */
        const data: FundingRequestFSFormDTO = {
          ...(this.loaded || initialFundingRequestFSForm),
          fs_form_7600a_use_g_invoicing: this.useGInvoicing,
          gt_c_number: this.gInvoiceNumber,
        };
        /* eslint-enable */
        await FinancialDetails.saveFundingRequestFormAndGInvoicing(data);
      }
    } catch (error) {
      console.log(error);
    }
    return true;
  }

  private hasChanged(): boolean {
    // this if statement is used for the temporary use_g_invoicing migration
    // it can be safely removed after all packages have been updated
    if (!this.loaded?.fs_form_7600a_use_g_invoicing) {
      return true;
    }
    return hasChanges(this.currentData, this.savedData);
  }
}
</script>
