<template>
  <v-form ref="form" lazy-validation>
    <v-container fluid class="container-max-width">
      <v-row>
        <v-col class="col-12">
          <h1 class="page-header mb-3">
            Let’s gather details for your FS Form 7600B
          </h1>
          <div class="copy-max-width">
            <ATATRadioGroup
              class="max-width-640"
              id="GInvoicingOptions"
              legend="Did you use G-Invoicing for your FS Form 7600B?"
              :items="gInvoicingOptions"
              :value.sync="useGInvoicing"
              :rules="[$validators.required('Please select an option')]"
            />
          </div>
          <div v-show="useGInvoicing === 'YES'">
            <hr class="mt-5" />
            <!-- eslint-disable max-len -->
            <ATATSearch
              id="OrderNumber"
              placeHolder="Find your order in G-Invoicing"
              label="Order Number"
              tooltipText="This is a 20-character value (including hyphens) generated by G-Invoicing."
              :width="'388px'"
              :hideHelpTextOnError="true"
              :validate-on-blur="true"
              :value.sync="orderNumber"
              helpText="Format: OYYMM-000-000-000000"
              searchType="G-Invoicing"
              gInvoicingSearchType="OrderNumber"
              @onGInvoiceSearchComplete="onGInvoiceSearchComplete"
              :rules="[
                $validators.isMaskValid(
                  ['O[0-9]{4}\-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$'],
                  `Your Order Number should be 20 characters (including hyphens) and use the format: OYYMM-000-000-000000.`,
                  true
                ),
                $validators.required('Please provide an Order number.'),
              ]"
              :triggerSearch="triggerSearch"
            />
            <!-- eslint-enable -->
          </div>
          <div v-show="useGInvoicing === 'NO'">
            <hr class="mt-5" />
            <div style="width: 460px">
              <ATATTextField
                id="OrderNumber"
                label="Order Number"
                tooltipText="This is a 20-character value (including hyphens) generated by G-Invoicing. Your Order Number is located in the top section of your <strong>FS Form 7600B.</strong>"
                :width="'388'"
                :hideHelpTextOnError="true"
                :validate-on-blur="true"
                :value.sync="orderNumber"
                helpText="Format: OYYMM-000-000-000000"
                :rules="[
                  $validators.isMaskValid(
                    ['O[0-9]{4}\-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$'],
                    `Your Order Number should be 20 characters (including hyphens) and use the format: OYYMM-000-000-000000.`,
                    true
                  ),
                  $validators.required('Please provide an Order number.'),
                ]"
              />
            </div>
            <hr class="mv-5" />
            <h2 class="h2 pb-5">Upload your FS Form 7600B</h2>
            <ATATFileUpload
              :validFileFormats="validFileFormats"
              :attachmentServiceName="attachmentServiceName"
              :maxFileSizeInBytes="maxFileSizeInBytes"
              id="FundingPlan"
              @delete="onRemoveAttachment"
              fileListTitle="Your files"
              :invalidFiles.sync="invalidFiles"
              :maxNumberOfFiles="1"
              :multiplesAllowed="false"
              :validFiles.sync="uploadedFiles"
              :requiredMessage="requiredMessage"
              :rules="getRulesArray()"
              :confirmRemoval="true"
              :confirmRemovalTitle="'Delete funding document?'"
              :confirmRemovalMessage="confirmRemoveFileMessage"
            />
          </div>
        </v-col>
      </v-row>
    </v-container>
  </v-form>
</template>
<script lang="ts">
import { ValidationResult, invalidFile, uploadingFile } from "types/Global";
import { Component, Vue, toNative } from "vue-facing-decorator";
import ATATRadioGroup from "@/components/ATATRadioGroup.vue";
import ATATSearch from "@/components/ATATSearch.vue";
import GInvoiceLearnMore from "@/steps/10-FinancialDetails/GInvoiceLearnMore.vue";
import SlideoutPanel from "@/store/slideoutPanel/index";
import { TABLENAME as FUNDING_REQUEST_FSFORM_TABLE } from "@/api/fundingRequestFSForm";
import Attachments from "@/store/attachments";

import { RadioButton, SlideoutPanelContent } from "../../../types/Global";
import FinancialDetails, {
  initialFundingRequestFSForm,
} from "@/store/financialDetails";

import SaveOnLeave from "@/mixins/saveOnLeave";
import { hasChanges } from "@/helpers";
import ATATTextField from "@/components/ATATTextField.vue";
import ATATFileUpload from "@/components/ATATFileUpload.vue";
import { AttachmentDTO, FundingRequestFSFormDTO } from "@/api/models";
import AcquisitionPackage from "@/store/acquisitionPackage";

@Component({
  mixins: [SaveOnLeave],
  components: {
    ATATRadioGroup,
    ATATSearch,
    ATATTextField,
    ATATFileUpload,
    GInvoiceLearnMore,
  },
})
class Upload7600 extends Vue {
  // radio options
  public useGInvoicing = "";
  private gInvoicingOptions: RadioButton[] = [
    {
      id: "Yes",
      label: "Yes. My Order Number is in G-Invoicing.",
      value: "YES",
    },
    {
      id: "No",
      label: "No. I would like to upload my 7600B form.",
      value: "NO",
    },
  ];

  // gtc number text field
  public orderNumber = "";
  private triggerSearch = false;

  // file upload
  private validFileFormats = ["pdf"];
  private attachmentServiceName = FUNDING_REQUEST_FSFORM_TABLE;
  private maxFileSizeInBytes = 1073741824;
  private invalidFiles: invalidFile[] = [];
  private uploadedFiles: uploadingFile[] = [];
  private loaded: FundingRequestFSFormDTO | null = null;
  private gInvoiceSearchValid = false;

  private requiredMessage =
    "You must include an authorized 7600B for this acquisition. " +
    "Upload your missing document, " +
    "or select Back to choose another method for transferring funds.";

  public openSlideoutPanel(e: Event): void {
    if (e?.currentTarget) {
      SlideoutPanel.openSlideoutPanel((e.currentTarget as HTMLElement).id);
    }
  }

  private onGInvoiceSearchComplete(validity: boolean) {
    this.gInvoiceSearchValid = validity;
  }

  public get currentData() {
    return {
      useGInvoicing: this.useGInvoicing,
      orderNumber: this.orderNumber,
    };
  }

  public savedData = {
    useGInvoicing: "",
    orderNumber: "",
  };

  private get confirmRemoveFileMessage() {
    return (
      (this.uploadedFiles?.[0]?.fileName
        ? `"${this.uploadedFiles[0].fileName}"`
        : "This file") +
      " will be permanently removed " +
      "from your acquisition package. This action cannot be undone."
    );
  }

  // rules array dynamically created based on the invalid
  // files returned from the child component
  // `ATATFileUpload.vue`
  private getRulesArray(): ((v: string) => ValidationResult)[] {
    if (this.useGInvoicing === "YES") return [];
    const rulesArr: ((v: string) => ValidationResult)[] = [];

    rulesArr.push(this.$validators.required(this.requiredMessage));

    this.invalidFiles.forEach((iFile) => {
      rulesArr.push(
        this.$validators.isFileValid(
          iFile.file,
          this.validFileFormats,
          this.maxFileSizeInBytes,
          iFile.doesFileExist,
          iFile.SNOWError,
          iFile.statusCode
        )
      );
    });

    return rulesArr;
  }

  async onRemoveAttachment(file: uploadingFile): Promise<void> {
    try {
      if (file) {
        const key = this.attachmentServiceName;
        const attachmentId = file.attachmentId;
        const recordId = file.recordId;
        await Attachments.removeAttachment({
          key,
          attachmentId,
          recordId,
        });

        //get updated data
        await this.loadFundingRequestData();
      }
    } catch (error) {
      console.error(`error removing attachment with id ${file?.attachmentId}`);
    }
  }

  async loadFundingRequestData(): Promise<void> {
    this.loaded = await FinancialDetails.loadFundingRequestFSForm();
    this.orderNumber = this.loaded?.order_number ?? "";

    // temporarily infering this useGInvoicing until accounts are properly migrated
    // if the new form a/b independant use_g_invoicing is already saved use that
    // else if the previous joined use_g_invoicing is saved, use that
    // else infer the use_g_invoicing by existence of form_attachment
    if (this.loaded?.fs_form_7600b_use_g_invoicing) {
      this.useGInvoicing = this.loaded.fs_form_7600b_use_g_invoicing;
    } else if (this.loaded?.use_g_invoicing) {
      this.useGInvoicing = this.loaded?.use_g_invoicing;
    } else {
      this.useGInvoicing = this.loaded?.fs_form_7600b_attachment ? "NO" : "YES";
    }

    this.savedData = {
      useGInvoicing: this.useGInvoicing,
      orderNumber: this.orderNumber,
    };

    if (this.orderNumber && this.useGInvoicing) this.triggerSearch = true;
  }

  /**
   * Constructs an array of attachment table primary key sys ids based on the forms
   * uploaded. Uses the array to load the attachments.
   */
  async loadAttachments(): Promise<void> {
    const attachmentSysIds = [];
    if (
      this.loaded?.fs_form_7600b_attachment &&
      this.loaded?.fs_form_7600b_attachment.length > 0
    ) {
      attachmentSysIds.push(this.loaded?.fs_form_7600b_attachment);
    }
    const attachments = await Attachments.getAttachmentsBySysIds({
      serviceKey: FUNDING_REQUEST_FSFORM_TABLE,
      sysIds: attachmentSysIds,
    });
    const uploadedFiles = attachments.map((attachment: AttachmentDTO) => {
      const file = new File([], attachment.file_name, {
        lastModified: Date.parse(attachment.sys_created_on ?? ""),
      });
      const upload: uploadingFile = {
        attachmentId: attachment.sys_id ?? "",
        fileName: attachment.file_name,
        file: file,
        created: file.lastModified,
        progressStatus: 100,
        link: attachment.download_link ?? "",
        recordId: attachment.table_sys_id,
        isErrored: false,
        isUploaded: true,
      };
      return upload;
    });
    this.uploadedFiles = [...uploadedFiles];
  }

  async loadOnEnter(): Promise<void> {
    try {
      await this.loadFundingRequestData();
      await this.loadAttachments();
    } catch (error) {
      throw new Error("an error occurred loading funding plans data");
    }
  }

  public async mounted(): Promise<void> {
    const slideoutPanelContent: SlideoutPanelContent = {
      component: GInvoiceLearnMore,
      title: "Learn More",
    };
    await SlideoutPanel.setSlideoutPanelComponent(slideoutPanelContent);
    await this.loadOnEnter();
  }

  protected async saveOnLeave(): Promise<boolean> {
    if (this.gInvoiceSearchValid !== true && this.useGInvoicing === "YES")
      return false;
    await AcquisitionPackage.setValidateNow(true);
    // file upload / saving
    try {
      if (this.hasChanged()) {
        this.loaded = await FinancialDetails.loadFundingRequestFSForm();
        /* eslint-disable camelcase */
        const data: FundingRequestFSFormDTO = {
          ...(this.loaded || initialFundingRequestFSForm),
          fs_form_7600b_use_g_invoicing: this.useGInvoicing,
          order_number: this.orderNumber,
        };
        /* eslint-enable */
        await FinancialDetails.saveFundingRequestFormBAndOrderNumber(data);
      }
    } catch (error) {
      console.log(error);
    }
    return true;
  }

  private hasChanged(): boolean {
    // this if statement is used for the temporary use_g_invoicing migration
    // it can be safely removed after all packages have been updated
    if (!this.loaded?.fs_form_7600b_use_g_invoicing) {
      return true;
    }
    return hasChanges(this.currentData, this.savedData);
  }
}

export default toNative(Upload7600)
</script>
