<template>
  <v-container class="container-max-width mb-7" fluid>
    <v-row>
      <v-col class="col-12">
        <h1 class="page-header">
          Let’s gather info about your 7600A and 7600B
        </h1>
        <div class="mt-10">
          <ATATTextField
            id="GeneralTermsAndConditions"
            label="General Terms & Conditions (GT&C) Number"
            helpText="Format: AYYMM-000-000-000000"
            :tooltipText="generalTermsAndConditionsToolTips"
            class="_input-max-width"
            :validate-on-blur="true"
            :rules="[
              $validators.required('Please enter your GT&C Number.'),
              $validators.isMaskValid(
                ['A[0-9]{4}\-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$'],
                `Your GT&C Number should be 20 or 22 characters (including hyphens
                    and periods) and use the format:<ul>
                    <li>AYYMM-000-000-000000</li>
                    <li>AYYMM-000-000-000000.0 (with version number)</li></ul>`,
                true
              ),
            ]"
            :value.sync="gtcNumber"
            hideHelpTextOnErrors="true"
          />
        </div>
        <div class="mt-10">
          <ATATTextField
            id="OrderNumber"
            label="Order Number"
            helpText="Format: OYYMM-000-000-000000"
            :tooltipText="orderNumberToolTips"
            class="_input-max-width"
            :rules="[
              $validators.required('Please enter your Order Number.'),
              $validators.isMaskValid(
                ['O[0-9]{4}\-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$'],
                `Your Order Number should be 20 or 22 characters (including hyphens 
                    and periods) and use the format:<ul>
                    <li>OYYMM-000-000-000000</li>
                    <li>OYYMM-000-000-000000.0 (with version number)</li></ul>`,
                true
              ),
            ]"
            :value.sync="orderNumber"
            hideHelpTextOnErrors="true"
          />
        </div>
        <hr class="base-lighter" />

        <h4 class="h4 text-base-darkest font-size-24 mb-5">
          Upload your 7600A and 7600B
        </h4>
        <ATATFileUpload
          :validFileFormats="validFileFormats"
          :attachmentServiceName="attachmentServiceName"
          :maxFileSizeInBytes="maxFileSizeInBytes"
          id="FundingPlan"
          @delete="onRemoveAttachment"
          fileListTitle="Your files"
          :invalidFiles.sync="invalidFiles"
          :maxNumberOfFiles="2"
          :validFiles.sync="uploadedFiles"
          :requiredMessage="requiredMessage"
          :rules="getRulesArray()"
        />
        <ATATAlert
          id="UPload7600Alert"
          v-show="uploadedFiles.length > 0 && uploadedFiles.length < 2"
          type="warning"
          class="mt-10"
        >
          <template v-slot:content>
            <p class="mb-0">
              You may be missing a funding document. Please ensure that both
              authorized forms are uploaded. If your 7600A and 7600B were
              combined into a single file before uploading, ignore this message.
            </p>
          </template>
        </ATATAlert>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
/* eslint camelcase: 0, prefer-const: 1 */
import { Component, Mixins, Watch } from "vue-property-decorator";
import ATATTextField from "@/components/ATATTextField.vue";
import ATATFileUpload from "../../components/ATATFileUpload.vue";
import ATATErrorValidation from "@/components/ATATErrorValidation.vue";
import ATATAlert from "@/components/ATATAlert.vue";
import { invalidFile, uploadingFile } from "types/Global";
import { TABLENAME as FUNDING_REQUEST_FSFORM_TABLE } from "@/api/fundingRequestFSForm";

// import { hasChanges } from "@/helpers";
// import AcquisitionPackage from "@/store/acquisitionPackage";
import SaveOnLeave from "@/mixins/saveOnLeave";
import Attachments from "@/store/attachments";
import { AttachmentDTO, FundingRequestFSFormDTO } from "@/api/models";
import FinancialDetails, {initialFundingRequestFSForm} from "@/store/financialDetails";
import { hasChanges } from "@/helpers";
import { AttachmentServiceCallbacks } from "@/services/attachment";

let generalTermsAndConditionsToolTips = "This is a unique 20-character value";
generalTermsAndConditionsToolTips +=
  "generated by G-Invoicing. You can find your GT&C Number";
generalTermsAndConditionsToolTips +=
  " in the top section of your <strong>FS Form 7600A.</strong>";

let orderNumberToolTips =
  "This is a unique 20-character value generated by G-Invoicing. ";
orderNumberToolTips +=
  "You can find your Order Number in the top section of your <strong>FS Form 7600B.</strong>";

const GTCMRegex = /A[0-9]{4}-[0-9]{3}-[0-9]{3}-[0-9]{6}(\.[0-9])?$/gm;

@Component({
  components: {
    ATATTextField,
    ATATFileUpload,
    ATATErrorValidation,
    ATATAlert,
  },
})
export default class Upload7600 extends Mixins(SaveOnLeave) {
  private attachmentServiceName = FUNDING_REQUEST_FSFORM_TABLE;
  private generalTermsAndConditionsToolTips = generalTermsAndConditionsToolTips;
  private orderNumberToolTips = orderNumberToolTips;
  private uploadedFiles: uploadingFile[] = [];
  private invalidFiles: invalidFile[] = [];
  private validFileFormats = ["pdf"];
  private maxFileSizeInBytes = 1073741824;
  private gtcNumber = "";
  private orderNumber = "";
  private showWarning = false;
  private loaded: FundingRequestFSFormDTO | null = null;
 
  private requiredMessage =
    "You must include an authorized 7600A and 7600B for this acquisition. " +
    "Please upload your missing documents," +
    "or select Back to choose another method for transferring funds.";

  private saved: {gtcNumber: string, orderNumber: string} = {
    gtcNumber: "",
    orderNumber: ""
  };
  

  get current(): {gtcNumber: string, orderNumber: string} {
    return {

      gtcNumber: this.gtcNumber,
      orderNumber: this.orderNumber
    }     
  }

  // rules array dynamically created based on the invalid
  // files returned from the child component
  // `ATATFileUpload.vue`
  private getRulesArray(): ((v: string) => string | true | undefined)[] {
    //eslint-disable-next-line prefer-const
    let rulesArr: ((v: string) => string | true | undefined)[] = [];

    rulesArr.push(this.$validators.required(this.requiredMessage));

    this.invalidFiles.forEach((iFile) => {
      rulesArr.push(
        this.$validators.isFileValid(
          iFile.file,
          this.validFileFormats,
          this.maxFileSizeInBytes,
          iFile.doesFileExist,
          iFile.SNOWError,
          iFile.statusCode
        )
      );
    });

    return rulesArr;
  }

  async onRemoveAttachment(file: uploadingFile): Promise<void> {
    try {
      if (file) {
        const key = this.attachmentServiceName;
        const attachmentId = file.attachmentId;
        const recordId = file.recordId;
        await Attachments.removeAttachment({
          key,
          attachmentId,
          recordId,
        });

        //get updated data
        await this.loadFundingRequestData();
      }
    } catch (error) {
      console.error(`error removing attachment with id ${file?.attachmentId}`);
    }
  }

  @Watch("uploadedFiles")
  private onUploadedFilesChanged(): void {
    this.showWarning =
      this.uploadedFiles.length > 0 && this.uploadedFiles.length < 2;
  }

  async loadFundingRequestData(): Promise<void>{
    this.loaded = await FinancialDetails.loadFundingRequestFSForm();
    this.saved = {
      gtcNumber: this.loaded.gt_c_number,
      orderNumber: this.loaded.order_number
    }
    this.gtcNumber = this.loaded.gt_c_number;
    this.orderNumber = this.loaded.order_number;
  }

  /**
   * Constructs an array of attachment table primary key sys ids based on the forms
   * uploaded. Uses the array to load the attachments.
   */
  async loadAttachments(): Promise<void>{
    const attachmentSysIds = [];
    if (this.loaded?.fs_form_7600a_attachment && this.loaded?.fs_form_7600a_attachment.length > 0) {
      attachmentSysIds.push(this.loaded?.fs_form_7600a_attachment)
    }
    if (this.loaded?.fs_form_7600b_attachment && this.loaded?.fs_form_7600b_attachment.length > 0) {
      attachmentSysIds.push(this.loaded?.fs_form_7600b_attachment)
    }
    const attachments = await Attachments.getAttachmentsBySysIds({
      serviceKey: FUNDING_REQUEST_FSFORM_TABLE,
      sysIds: attachmentSysIds 
    });
    const uploadedFiles = attachments.map((attachment: AttachmentDTO) => {
      const file = new File([], attachment.file_name, {
        lastModified: Date.parse(attachment.sys_created_on || "")
      });
      const upload: uploadingFile = {
        attachmentId: attachment.sys_id || "",
        fileName: attachment.file_name,
        file: file,
        created: file.lastModified,
        progressStatus: 100,
        link: attachment.download_link || "",
        recordId: attachment.table_sys_id,
        isErrored: false,
        isUploaded: true
      }
      return upload;
    });
    this.uploadedFiles = [...uploadedFiles];
  }

  async loadOnEnter(): Promise<void> {
    try {

      await this.loadFundingRequestData();
      await this.loadAttachments();

    } catch (error) {
      throw new Error("an error occurred loading funding plans data");
    }
  }

  public async mounted(): Promise<void> {
    await this.loadOnEnter();
  }

  protected async saveOnLeave(): Promise<boolean> {
    try {
      if (this.hasChanged()) {
        this.loaded = await FinancialDetails.loadFundingRequestFSForm();
        //eslint-disable-next-line prefer-const
        let data: FundingRequestFSFormDTO = {
          ...this.loaded || initialFundingRequestFSForm,
          order_number: this.current.orderNumber,
          gt_c_number: this.current.gtcNumber,
        }
        await FinancialDetails.saveFundingRequestFSForm(data);
      }
    } catch (error) {
      console.log(error);
    }
    return true;
  }

  private hasChanged(): boolean {
    return hasChanges(this.current, this.saved);
     
  }

  private showDefaultValidation(): boolean {
    if (this.gtcNumber.length === 0) {
      return true;
    }

    return GTCMRegex.test(this.gtcNumber);
  }
}
</script>
