<template>
  <div class="mb-7">
    <v-container class="container-max-width" fluid>
      <v-row>
        <v-col class="col-12">
          <h1 class="page-header">
            Let’s gather info about your 7600A and 7600B
          </h1>
          <div class="mt-10">
            <ATATTextField
              id="GeneralTermsAndConditions"
              label="General Terms & Conditions (GT&C) Number"
              helpText="Format: AYYMM-000-000-000000"
              :tooltipText="generalTermsAndConditionsToolTips"
              class="_input-max-width"
              :rules="[$validators.required('Please enter your GT&C number.')]"
            />
          </div>
          <div class="mt-10">
            <ATATTextField
              id="OrderNumber"
              label="Order Number"
              helpText="Format: OYYMM-000-000-000000"
              :tooltipText="orderNumberToolTips"
              class="_input-max-width"
              :rules="[$validators.required('Please enter your order number.')]"
            />
          </div>
          <hr class="base-lighter mt-10 mb-8" />

          <di class="mt-10">
            <h4 class="h4 text-base-darkest font-size-24 mb-5">Upload your 7600A and 7600B</h4>
            <ATATFileUpload
              :validFileFormats="validFileFormats"
              attachmentServiceName="FundingPlans"
              :maxFileSizeInBytes="maxFileSizeInBytes"
              id="FundingPlan"
              @delete="onRemoveAttachment"
              :invalidFiles.sync="invalidFiles"
              :validFiles.sync="uploadedFiles"
              :rules="getRulesArray()"
            />
          </di>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script lang="ts">
/* eslint-disable camelcase */
import { Component, Mixins } from "vue-property-decorator";
import ATATTextField from "@/components/ATATTextField.vue";
import ATATFileUpload from "../../components/ATATFileUpload.vue";
import { invalidFile, uploadingFile } from "types/Global";

// import { hasChanges } from "@/helpers";
// import AcquisitionPackage from "@/store/acquisitionPackage";
import SaveOnLeave from "@/mixins/saveOnLeave";
import { AttachmentTables } from "@/api";
import Attachments from "@/store/attachments";

let generalTermsAndConditionsToolTips = "This is a unique 20-character value";
generalTermsAndConditionsToolTips +=
  "generated by G-Invoicing. You can find your GT&C number";
generalTermsAndConditionsToolTips +=
  " in the top section of your FS Form 7600A.";

let orderNumberToolTips =
  "This is a unique 20-character value generated by G-Invoicing. ";
orderNumberToolTips +=
  "You can find your order number in the top section of your FS Form 7600B.";

@Component({
  components: {
    ATATTextField,
    ATATFileUpload,
  },
})
export default class FundingPlanType extends Mixins(SaveOnLeave) {
  private generalTermsAndConditionsToolTips = generalTermsAndConditionsToolTips;
  private orderNumberToolTips = orderNumberToolTips;
   private uploadedFiles: uploadingFile[] = [];
  private invalidFiles: invalidFile[] = [];
  private validFileFormats = ["xlsx", "xls", "pdf"];
  private maxFileSizeInBytes = 1073741824;

  // rules array dynamically created based on the invalid
  // files returned from the child component
  // `ATATFileUpload.vue`
  private getRulesArray(): ((v: string) => string | true | undefined)[] {
    let rulesArr: ((v: string) => string | true | undefined)[] = [];

    this.invalidFiles.forEach((iFile) => {
      rulesArr.push(
        this.$validators.isFileValid(
          iFile.file,
          this.validFileFormats,
          this.maxFileSizeInBytes,
          iFile.doesFileExist,
          iFile.SNOWError,
          iFile.statusCode
        )
      );
    });
    return rulesArr;
  }

  async onRemoveAttachment(file: uploadingFile): Promise<void> {
    try {
      if (file) {
        const key = AttachmentTables.FundingPlans;
        const attachmentId = file.attachmentId;
        const recordId = file.recordId;
        await Attachments.removeAttachment({
          key,
          attachmentId,
          recordId,
        });
      }
    } catch (error) {
      console.error(`error removing attachment with id ${file?.attachmentId}`);
    }
  }

  public async loadOnEnter(): Promise<void> {
    //todo: load data
  }

  public async mounted(): Promise<void> {
    await this.loadOnEnter();
  }

  protected async saveOnLeave(): Promise<boolean> {
    try {
      if (this.hasChanged()) {
        //todo: save data
      }
    } catch (error) {
      console.log(error);
    }
    return true;
  }

  private hasChanged(): boolean {
    // return hasChanges(this.currentData, this.savedData);
    // todo fill out has changes
    return false;
  }
}
</script>
