<template>
  <div>
    <h1 class="page-header">
      Let’s work on price estimates for your performance requirements
    </h1>
    <p class="page-paragraph">
      Using the report generated from the previous screen, specify the projected price for each of
      your cloud service and support requirements. Edit any pre-filled details, as needed, to
      provide a more accurate description of what you are estimating (e.g., specific product/service
      names or configuration summaries generated by CSP calculator). We’ll use this info to
      populate total projected prices for each period of your task order later.
      <a role="button"
         id="OpenLearnMore"
         tabindex="0"
         @click="openSlideoutPanel"
         @keydown.enter="openSlideoutPanel"
         @keydown.space="openSlideoutPanel">
        View Price Estimate FAQs
      </a>
    </p>
    <div class="_price-estimates-accordion">
      <v-expansion-panels
        v-model="accordionClosed[index]"
        v-for="(classification, index) in instanceData"
        :id="'AnticipatedUserAndDataNeedsAccordion' + index"
        :key="index"
        class="mb-4"
        flat
      >
        <v-expansion-panel expand>
          <v-expansion-panel-header>
            <div class="d-flex justify-space-between">
              <div class="h4 _expansion-panel-header">
                {{classification.labelShort}}
                <span class="offering-number">
                  {{classification.offerings.length}}
                </span>
              </div>
            </div>
          </v-expansion-panel-header>
          <v-expansion-panel-content>
            <div class="_expansion-panel-content-header">
              <div>
                Service Name and Configuration Summary
              </div>
              <div>
                Estimated price per unit
              </div>
            </div>

          </v-expansion-panel-content>
        </v-expansion-panel>
      </v-expansion-panels>
    </div>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

import { Component } from "vue-property-decorator";
import SlideoutPanel from "@/store/slideoutPanel";
import { SlideoutPanelContent } from "../../../../types/Global";
// eslint-disable-next-line camelcase
/* eslint-disable camelcase */
import SlideOut_GatherPricesEstimates
  from "@/steps/10-FinancialDetails/IGCE/components/SlideOut_GatherPricesEstimates.vue";
import { buildClassificationLabel } from "@/helpers";
import ClassificationRequirements from "@/store/classificationRequirements";
import { SelectedClassificationLevelDTO } from "@/api/models";
import DescriptionOfWork from "@/store/descriptionOfWork";

@Component({
})
export default class GatherPriceEstimates extends Vue {

  public selectedClassifications: SelectedClassificationLevelDTO[] = []
  public accordionClosed: number[] = []
  public instanceData:any[] = []

  public buildClassificationLabel = buildClassificationLabel
  public openSlideoutPanel(e: Event): void {
    if (e && e.currentTarget) {
      const opener = e.currentTarget as HTMLElement;
      SlideoutPanel.openSlideoutPanel(opener.id);
    }
  }

  private async loadOnEnter(): Promise<void> {
    const classifications = await ClassificationRequirements.getSelectedClassificationLevels()
    this.selectedClassifications = classifications
      .sort((a,b) => a.impact_level > b.impact_level ? 1 : -1)
    this.accordionClosed = new Array(classifications.length).fill(0)
    this.selectedClassifications.forEach((classification)=>{
      // eslint-disable-next-line camelcase
      const classification_instance:{
        labelShort:string,
        sysId:string,
        offerings:Record<string,string>[]
      } = {
        labelShort: buildClassificationLabel(classification,'short',true),
        sysId:classification.sys_id|| "",
        offerings:[]
      }
      this.instanceData.push(classification_instance)
    })

    const dowObject = DescriptionOfWork.DOWObject
    dowObject.forEach((service)=>{
      const classificationOfferings:{
        IGCE_title:string,
        IGCE_description:string,
        monthly_price:number
      } = {
        IGCE_title:"",
        IGCE_description:"",
        monthly_price:0
      }
      const serviceName = service.serviceOfferingGroupId
      if(service.otherOfferingData){
        debugger
        service.otherOfferingData.forEach((offering)=>{
          if(offering.classificationLevel){
            this.instanceData.forEach((instance)=>{
              if(instance.sysId === offering.classificationLevel){
                if(offering.instanceNumber){
                  classificationOfferings.IGCE_title =
                    `${serviceName} - instance #${offering.instanceNumber}`;
                }else{
                  classificationOfferings.IGCE_title = serviceName;
                }
                const formData = `${offering.numberOfInstancesNeeded} x
                (${offering.environmentType}, virtual machines,
                ${offering.operatingSystemAndLicensing}, ${offering.numberOfVCPUs}
                 vCPUs, ${offering.memory} GB RAM,
                  ${offering.storageType}: ${offering.storageAmount} GB, general performance)`
                classificationOfferings.IGCE_description = formData || offering.anticipatedNeedUsage
                instance.offerings.push(classificationOfferings)
              }
            })
          }
        })
      }
      if(service.serviceOfferings){
        service.serviceOfferings.forEach((offering)=>{
          offering.classificationInstances?.forEach((classificationInstance)=>{
            this.instanceData.forEach((instance)=>{
              if(instance.sysID === classificationInstance.classificationLevelSysId){
                classificationOfferings.IGCE_title = `${serviceName} - ${offering.name}`;
                classificationOfferings.IGCE_description =
                  classificationInstance.anticipatedNeedUsage
                instance.offerings.push(classificationOfferings)
              }
            })
          })
        })
      }
    })
    console.log(dowObject)
    console.log(this.selectedClassifications)
    console.log(this.instanceData)
  }

  public async mounted(): Promise<void> {
    await this.loadOnEnter()
    const slideoutPanelContent: SlideoutPanelContent = {
      // eslint-disable-next-line camelcase
      component: SlideOut_GatherPricesEstimates,
      title: "Learn More",
    };
    await SlideoutPanel.setSlideoutPanelComponent(slideoutPanelContent);
  }
}
</script>

