name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOWS_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch # to use a different bump, include "#minor" or "#major" in the PR title/description
          INITIAL_VERSION: 1.22.2