---
name: Build and Deploy SPA

concurrency: deploy-spa

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  build:
    name: Build SPA
    runs-on: ubuntu-20.04
    steps:
      - name: Get build timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date --iso-8601=seconds)"
      - name: Configure npm caching
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Checkout code base
        uses: actions/checkout@v2
      - name: Install global dependencies
        run: |
          npm install -g @vue/cli
          npm i -g @vue/cli-service-global
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Generate build data file
        run: |
          cat <<EOF > dist/.build-data.json
          {
            "git_ref": "${{ github.ref }}",
            "git_sha": "${{ github.sha }}",
            "timestamp": "${{ steps.timestamp.outputs.timestamp }}"
          }
          EOF
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: atat-web-ui
          path: dist
  deploy:
    name: Deploy SPA to AWS
    runs-on: ubuntu-20.04
    needs: build
    steps:
      # Ensure that the account ID does not appear in any log messages in the pipeline
      - run: echo ::add-mask::${{ secrets.AWS_US_GOV_ACCOUNT_ID }}
      - name: Get deployment timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date --iso-8601=seconds)"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_US_GOV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_US_GOV_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
      - name: Download site artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: atat-web-ui
      - name: Generate deployment data file
        run: |
          cat <<EOF > .deployment-data.json
          {
            "git_ref": "${{ github.ref }}",
            "git_sha": "${{ github.sha }}",
            "timestamp": "${{ steps.timestamp.outputs.timestamp }}"
          }
          EOF
      - name: Upload site
        run: |
          aws s3 sync . s3://${{ secrets.AWS_US_GOV_BUCKET_NAME }} --delete --region us-gov-west-1
        working-directory: ${{ steps.download.outputs.download-path }}
