---
name: Run Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  assertPackageLockVersion:
    name: Ensure package-lock lockfileVersion has not changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check package-lock.json
        run: |
          errors=0
          for file in package-lock.json cdk/package-lock.json; do
            if [ "$(cat $file | jq -r .lockfileVersion)" != "1" ]; then
              echo "$file: lockfileVersion is invalid"
              errors=$(( errors + 1 ))
            else
              echo "$file: lockfileVersion is okay"
            fi
          done
          exit $errors
  lint:
    name: Lint the code base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - name: Install dependencies
        run: npm ci --verbose
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: true
          SUPPRESS_POSSUM: true
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - name: Install dependencies
        run: npm ci --verbose
      - name: Run Lint
        run: npm run lint
      - name: Run tests
        run: npm run test:unit
      - name: Run build
        run: npm run build
      - name: Archive coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: Archive SPA Artifact
        uses: actions/upload-artifact@v2
        with:
          name: atat-web-ui
          path: dist
      - name: "[Workaround] Fix lcov.info paths"
        # Make all paths in `lcov.info` relative instead of absolute
        run: |
          sed -i"" "s|SF:/home/runner/work/atat-web-ui/atat-web-ui/|SF:|" ./coverage/lcov.info 
      - name: Trigger SonarCloud
        # This step will fail for external collaborators
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
